/**
 * src/oracles/tables/characters.js
 * Source: Starforged Reference Guide pp.62-67
 */

export const ROLE = [
  { min: 1,   max: 2,   result: "Agent" },        { min: 3,   max: 4,   result: "AI" },
  { min: 5,   max: 6,   result: "Artisan" },      { min: 7,   max: 8,   result: "Assassin" },
  { min: 9,   max: 10,  result: "Bounty Hunter" },{ min: 11,  max: 12,  result: "Courier" },
  { min: 13,  max: 14,  result: "Crew" },          { min: 15,  max: 16,  result: "Criminal" },
  { min: 17,  max: 18,  result: "Cultist" },       { min: 19,  max: 20,  result: "Diplomat" },
  { min: 21,  max: 22,  result: "Engineer" },      { min: 23,  max: 24,  result: "Entertainer" },
  { min: 25,  max: 26,  result: "Explorer" },      { min: 27,  max: 28,  result: "Farmer" },
  { min: 29,  max: 30,  result: "Fugitive" },      { min: 31,  max: 32,  result: "Guard" },
  { min: 33,  max: 34,  result: "Guide" },         { min: 35,  max: 36,  result: "Healer" },
  { min: 37,  max: 38,  result: "Historian" },     { min: 39,  max: 40,  result: "Hunter" },
  { min: 41,  max: 42,  result: "Investigator" },  { min: 43,  max: 44,  result: "Laborer" },
  { min: 45,  max: 46,  result: "Lawkeeper" },     { min: 47,  max: 48,  result: "Leader" },
  { min: 49,  max: 50,  result: "Mercenary" },     { min: 51,  max: 52,  result: "Merchant" },
  { min: 53,  max: 54,  result: "Miner" },         { min: 55,  max: 56,  result: "Mystic" },
  { min: 57,  max: 58,  result: "Navigator" },     { min: 59,  max: 60,  result: "Outcast" },
  { min: 61,  max: 62,  result: "Pilgrim" },       { min: 63,  max: 64,  result: "Pilot" },
  { min: 65,  max: 66,  result: "Pirate" },        { min: 67,  max: 68,  result: "Preacher" },
  { min: 69,  max: 70,  result: "Prophet" },       { min: 71,  max: 72,  result: "Raider" },
  { min: 73,  max: 74,  result: "Researcher" },    { min: 75,  max: 76,  result: "Scavenger" },
  { min: 77,  max: 78,  result: "Scholar" },       { min: 79,  max: 80,  result: "Scout" },
  { min: 81,  max: 82,  result: "Shipwright" },    { min: 83,  max: 84,  result: "Smuggler" },
  { min: 85,  max: 86,  result: "Soldier" },       { min: 87,  max: 88,  result: "Spacer" },
  { min: 89,  max: 90,  result: "Technician" },    { min: 91,  max: 92,  result: "Thief" },
  { min: 93,  max: 95,  result: "Action + Theme", ref: "action_theme" },
  { min: 96,  max: 100, result: "Roll twice" },
];

export const GOAL = [
  { min: 1,   max: 2,   result: "Avenge a wrong" },
  { min: 3,   max: 4,   result: "Build a home" },
  { min: 5,   max: 7,   result: "Build a relationship" },
  { min: 8,   max: 10,  result: "Claim a resource" },
  { min: 11,  max: 12,  result: "Collect a debt" },
  { min: 13,  max: 14,  result: "Craft an object" },
  { min: 15,  max: 16,  result: "Cure an ill" },
  { min: 17,  max: 18,  result: "Defeat a rival" },
  { min: 19,  max: 20,  result: "Defend a person" },
  { min: 21,  max: 23,  result: "Defend a place" },
  { min: 24,  max: 25,  result: "Discover a truth" },
  { min: 26,  max: 27,  result: "End a conflict" },
  { min: 28,  max: 29,  result: "Escape a captor" },
  { min: 30,  max: 31,  result: "Fight injustice" },
  { min: 32,  max: 33,  result: "Find a person" },
  { min: 34,  max: 35,  result: "Forge an alliance" },
  { min: 36,  max: 37,  result: "Gain knowledge" },
  { min: 38,  max: 39,  result: "Gain riches" },
  { min: 40,  max: 41,  result: "Maintain order" },
  { min: 42,  max: 43,  result: "Make an agreement" },
  { min: 44,  max: 45,  result: "Obtain an object" },
  { min: 46,  max: 47,  result: "Pay a debt" },
  { min: 48,  max: 49,  result: "Protect a lifeform" },
  { min: 50,  max: 51,  result: "Protect a secret" },
  { min: 52,  max: 53,  result: "Prove worthiness" },
  { min: 54,  max: 55,  result: "Rebel against power" },
  { min: 56,  max: 57,  result: "Refute a falsehood" },
  { min: 58,  max: 59,  result: "Repair a technology" },
  { min: 60,  max: 61,  result: "Resolve a dispute" },
  { min: 62,  max: 63,  result: "Restore a relationship" },
  { min: 64,  max: 65,  result: "Sabotage a technology" },
  { min: 66,  max: 68,  result: "Secure a resource" },
  { min: 69,  max: 70,  result: "Seek redemption" },
  { min: 71,  max: 72,  result: "Seize power" },
  { min: 73,  max: 74,  result: "Solve a mystery" },
  { min: 75,  max: 76,  result: "Spread faith" },
  { min: 77,  max: 78,  result: "Travel to a place" },
  { min: 79,  max: 80,  result: "Undermine a relationship" },
  { min: 81,  max: 90,  result: "Action + Theme", ref: "action_theme" },
  { min: 91,  max: 100, result: "Roll twice" },
];

export const FIRST_LOOK = [
  { min: 1,   max: 2,   result: "Accented" },    { min: 3,   max: 3,   result: "Adorned" },
  { min: 4,   max: 6,   result: "Accompanied" }, { min: 7,   max: 8,   result: "Aged" },
  { min: 9,   max: 11,  result: "Aged" },         { min: 12,  max: 13,  result: "Alluring" },
  { min: 14,  max: 15,  result: "Armed" },        { min: 16,  max: 17,  result: "Armored" },
  { min: 18,  max: 20,  result: "Athletic" },     { min: 21,  max: 23,  result: "Attractive" },
  { min: 24,  max: 25,  result: "Augmented" },    { min: 26,  max: 27,  result: "Concealed" },
  { min: 28,  max: 30,  result: "Distracted" },   { min: 31,  max: 33,  result: "Eccentric" },
  { min: 34,  max: 35,  result: "Energetic" },    { min: 36,  max: 37,  result: "Flashy" },
  { min: 38,  max: 40,  result: "Graceful" },     { min: 41,  max: 43,  result: "Grim" },
  { min: 44,  max: 46,  result: "Haggard" },      { min: 47,  max: 49,  result: "Ill-equipped" },
  { min: 50,  max: 52,  result: "Imposing" },     { min: 53,  max: 55,  result: "Large" },
  { min: 56,  max: 57,  result: "Mutated" },      { min: 58,  max: 60,  result: "Plain" },
  { min: 61,  max: 62,  result: "Poised" },       { min: 63,  max: 65,  result: "Scarred" },
  { min: 66,  max: 68,  result: "Scruffy" },      { min: 69,  max: 71,  result: "Shifty" },
  { min: 72,  max: 73,  result: "Sickly" },       { min: 74,  max: 76,  result: "Slight" },
  { min: 77,  max: 78,  result: "Swaggering" },   { min: 79,  max: 81,  result: "Tattooed" },
  { min: 82,  max: 83,  result: "Threatened" },   { min: 84,  max: 85,  result: "Uncanny" },
  { min: 86,  max: 87,  result: "Visibly disabled" }, { min: 88, max: 90, result: "Weathered" },
  { min: 91,  max: 92,  result: "Well-equipped" },{ min: 93,  max: 95,  result: "Wiry" },
  { min: 96,  max: 97,  result: "Wounded" },      { min: 98,  max: 100, result: "Youthful" },
];

export const DISPOSITION = [
  { min: 1,   max: 6,   result: "Helpful" },
  { min: 7,   max: 14,  result: "Friendly" },
  { min: 15,  max: 22,  result: "Cooperative" },
  { min: 23,  max: 30,  result: "Curious" },
  { min: 31,  max: 40,  result: "Indifferent" },
  { min: 41,  max: 50,  result: "Suspicious" },
  { min: 51,  max: 60,  result: "Wanting" },
  { min: 61,  max: 70,  result: "Desperate" },
  { min: 71,  max: 78,  result: "Demanding" },
  { min: 79,  max: 86,  result: "Unfriendly" },
  { min: 87,  max: 94,  result: "Threatening" },
  { min: 95,  max: 100, result: "Hostile" },
];

// Given names, family names, and callsigns from Reference Guide pp.64-67
export const GIVEN_NAMES = [
  { min: 1,   max: 1,   result: "Aiden" },    { min: 2,   max: 2,   result: "Aisha" },
  { min: 3,   max: 3,   result: "Akira" },    { min: 4,   max: 4,   result: "Aleksa" },
  { min: 5,   max: 5,   result: "Aleph" },    { min: 6,   max: 6,   result: "Amara" },
  { min: 7,   max: 7,   result: "Amaru" },    { min: 8,   max: 8,   result: "Amelia" },
  { min: 9,   max: 9,   result: "Amiri" },    { min: 10,  max: 10,  result: "Andrés" },
  { min: 11,  max: 11,  result: "Anika" },    { min: 12,  max: 12,  result: "Annora" },
  { min: 13,  max: 13,  result: "Aphelion" }, { min: 14,  max: 14,  result: "Aryan" },
  { min: 15,  max: 15,  result: "Ash" },      { min: 16,  max: 16,  result: "Asha" },
  { min: 17,  max: 17,  result: "Astrid" },   { min: 18,  max: 18,  result: "Axel" },
  { min: 19,  max: 19,  result: "Ayako" },    { min: 20,  max: 20,  result: "Ayu" },
  { min: 21,  max: 21,  result: "Bastian" },  { min: 22,  max: 22,  result: "Bek" },
  { min: 23,  max: 23,  result: "Blackbird" },{ min: 24,  max: 24,  result: "Bram" },
  { min: 25,  max: 25,  result: "Brynn" },    { min: 26,  max: 26,  result: "Cassidy" },
  { min: 27,  max: 27,  result: "Celia" },    { min: 28,  max: 28,  result: "Cinder" },
  { min: 29,  max: 29,  result: "Corey" },    { min: 30,  max: 30,  result: "Dag" },
  { min: 31,  max: 31,  result: "Dani" },     { min: 32,  max: 32,  result: "Decker" },
  { min: 33,  max: 33,  result: "Deja" },     { min: 34,  max: 34,  result: "Dex" },
  { min: 35,  max: 35,  result: "Doran" },    { min: 36,  max: 36,  result: "Echo" },
  { min: 37,  max: 37,  result: "Eren" },     { min: 38,  max: 38,  result: "Eris" },
  { min: 39,  max: 39,  result: "Erlin" },    { min: 40,  max: 40,  result: "Evander" },
  { min: 41,  max: 41,  result: "Faye" },     { min: 42,  max: 42,  result: "Fenris" },
  { min: 43,  max: 43,  result: "Finn" },     { min: 44,  max: 44,  result: "Flux" },
  { min: 45,  max: 45,  result: "Ghost" },    { min: 46,  max: 46,  result: "Glitch" },
  { min: 47,  max: 47,  result: "Juro" },     { min: 48,  max: 48,  result: "Kaisa" },
  { min: 49,  max: 49,  result: "Karthik" },  { min: 50,  max: 50,  result: "Kayla" },
  { min: 51,  max: 51,  result: "Kei" },      { min: 52,  max: 52,  result: "Kiana" },
  { min: 53,  max: 53,  result: "Kieran" },   { min: 54,  max: 54,  result: "Kierra" },
  { min: 55,  max: 55,  result: "Kimora" },   { min: 56,  max: 56,  result: "Kiri" },
  { min: 57,  max: 57,  result: "Kirsa" },    { min: 58,  max: 58,  result: "Kwan" },
  { min: 59,  max: 59,  result: "Kylar" },    { min: 60,  max: 60,  result: "Landry" },
  { min: 61,  max: 61,  result: "Logan" },    { min: 62,  max: 62,  result: "Lowell" },
  { min: 63,  max: 63,  result: "Lucas" },    { min: 64,  max: 64,  result: "Curtis" },
  { min: 65,  max: 65,  result: "Luna" },     { min: 66,  max: 66,  result: "Lux" },
  { min: 67,  max: 67,  result: "Mae" },      { min: 68,  max: 68,  result: "Mako" },
  { min: 69,  max: 69,  result: "Malachi" },  { min: 70,  max: 70,  result: "Marin" },
  { min: 71,  max: 71,  result: "Mira" },     { min: 72,  max: 72,  result: "Miria" },
  { min: 73,  max: 73,  result: "Nadia" },    { min: 74,  max: 74,  result: "Niran" },
  { min: 75,  max: 75,  result: "Nova" },     { min: 76,  max: 76,  result: "Nyx" },
  { min: 77,  max: 77,  result: "Orin" },     { min: 78,  max: 78,  result: "Orion" },
  { min: 79,  max: 79,  result: "Pari" },     { min: 80,  max: 80,  result: "Patch" },
  { min: 81,  max: 81,  result: "Pia" },      { min: 82,  max: 82,  result: "Quinn" },
  { min: 83,  max: 83,  result: "Roland" },   { min: 84,  max: 84,  result: "Rowena" },
  { min: 85,  max: 85,  result: "Sage" },     { min: 86,  max: 86,  result: "Saren" },
  { min: 87,  max: 87,  result: "Shen" },     { min: 88,  max: 88,  result: "Talia" },
  { min: 89,  max: 89,  result: "Tomiko" },   { min: 90,  max: 90,  result: "Ulan" },
  { min: 91,  max: 91,  result: "Valda" },    { min: 92,  max: 92,  result: "Venri" },
  { min: 93,  max: 93,  result: "Vesper" },   { min: 94,  max: 94,  result: "Vuldar" },
  { min: 95,  max: 95,  result: "William" },  { min: 96,  max: 96,  result: "Yelena" },
  { min: 97,  max: 97,  result: "Zakia" },    { min: 98,  max: 98,  result: "Zari" },
  { min: 99,  max: 99,  result: "Zev" },      { min: 100, max: 100, result: "Zoya" },
];

export const FAMILY_NAMES = [
  { min: 1,   max: 2,   result: "Adler" },    { min: 3,   max: 4,   result: "Bai" },
  { min: 5,   max: 6,   result: "Barbosa" },  { min: 7,   max: 8,   result: "Beckett" },
  { min: 9,   max: 10,  result: "Bond" },     { min: 11,  max: 12,  result: "Booker" },
  { min: 13,  max: 14,  result: "Buhari" },   { min: 15,  max: 16,  result: "Darwin" },
  { min: 17,  max: 18,  result: "Duval" },    { min: 19,  max: 20,  result: "Dykstra" },
  { min: 21,  max: 22,  result: "Freeman" },  { min: 23,  max: 24,  result: "Gray" },
  { min: 25,  max: 26,  result: "Hammond" },  { min: 27,  max: 28,  result: "Hawking" },
  { min: 29,  max: 30,  result: "Hobbs" },    { min: 31,  max: 32,  result: "Holland" },
  { min: 33,  max: 34,  result: "Hunter" },   { min: 35,  max: 36,  result: "Jen" },
  { min: 37,  max: 38,  result: "Mihara" },   { min: 39,  max: 40,  result: "Nazari" },
  { min: 41,  max: 42,  result: "O'Niel" },   { min: 43,  max: 44,  result: "Pearson" },
  { min: 45,  max: 46,  result: "Petrov" },   { min: 47,  max: 48,  result: "Salvi" },
  { min: 49,  max: 50,  result: "Sato" },     { min: 51,  max: 52,  result: "Savela" },
  { min: 53,  max: 54,  result: "Sedano" },   { min: 55,  max: 56,  result: "Shelton" },
  { min: 57,  max: 58,  result: "Silvius" },  { min: 59,  max: 60,  result: "Stark" },
  { min: 61,  max: 62,  result: "Sterling" }, { min: 63,  max: 64,  result: "Stirling" },
  { min: 65,  max: 66,  result: "Takara" },   { min: 67,  max: 68,  result: "Vandu" },
  { min: 69,  max: 70,  result: "Vayan" },    { min: 71,  max: 72,  result: "Vega" },
  { min: 73,  max: 74,  result: "Volkov" },   { min: 75,  max: 76,  result: "Wolfe" },
  { min: 77,  max: 78,  result: "Winter" },   { min: 79,  max: 80,  result: "Zhang" },
  { min: 81,  max: 100, result: "Roll again (paired name)" },
];

export const CALLSIGNS = [
  { min: 1,   max: 2,   result: "Anvil" },    { min: 3,   max: 4,   result: "Badger" },
  { min: 5,   max: 6,   result: "Banshee" },  { min: 7,   max: 8,   result: "Blade" },
  { min: 9,   max: 10,  result: "Bloodshot" },{ min: 11,  max: 12,  result: "Bullseye" },
  { min: 13,  max: 14,  result: "Chandra" },  { min: 15,  max: 16,  result: "Cobra" },
  { min: 17,  max: 18,  result: "Comet" },    { min: 19,  max: 20,  result: "Cutlass" },
  { min: 21,  max: 22,  result: "Dagger" },   { min: 23,  max: 24,  result: "Dancer" },
  { min: 25,  max: 26,  result: "Demon" },    { min: 27,  max: 28,  result: "Drake" },
  { min: 29,  max: 30,  result: "Eclipse" },  { min: 31,  max: 32,  result: "Ember" },
  { min: 33,  max: 34,  result: "Exile" },    { min: 35,  max: 36,  result: "Falcon" },
  { min: 37,  max: 38,  result: "Fang" },     { min: 39,  max: 40,  result: "Fixer" },
  { min: 41,  max: 42,  result: "Ghost" },    { min: 43,  max: 44,  result: "Grudge" },
  { min: 45,  max: 46,  result: "Gunner" },   { min: 47,  max: 48,  result: "Hammer" },
  { min: 49,  max: 50,  result: "Hush" },     { min: 51,  max: 52,  result: "Ironclad" },
  { min: 53,  max: 54,  result: "Jackal" },   { min: 55,  max: 56,  result: "Jackpot" },
  { min: 57,  max: 58,  result: "Jester" },   { min: 59,  max: 60,  result: "Link" },
  { min: 61,  max: 62,  result: "Longshot" }, { min: 63,  max: 64,  result: "Mainframe" },
  { min: 65,  max: 66,  result: "Mantis" },   { min: 67,  max: 68,  result: "Mimic" },
  { min: 69,  max: 70,  result: "Mole" },     { min: 71,  max: 72,  result: "Monarch" },
  { min: 73,  max: 74,  result: "Mongoose" }, { min: 75,  max: 76,  result: "Nails" },
  { min: 77,  max: 78,  result: "Ogre" },     { min: 79,  max: 80,  result: "Omega" },
  { min: 81,  max: 82,  result: "Overload" }, { min: 83,  max: 84,  result: "Packrat" },
  { min: 85,  max: 86,  result: "Paladin" },  { min: 87,  max: 88,  result: "Phantom" },
  { min: 89,  max: 90,  result: "Reaper" },   { min: 91,  max: 92,  result: "Sable" },
  { min: 93,  max: 94,  result: "Splinter" }, { min: 95,  max: 96,  result: "Static" },
  { min: 97,  max: 98,  result: "Stinger" },  { min: 99,  max: 100, result: "Wraith" },
];
