/**
 * src/oracles/tables/creatures.js
 * Source: Starforged Reference Guide pp.68-71
 */

export const ENVIRONMENT = [
  { min: 1,  max: 5,   result: "Space" },
  { min: 6,  max: 15,  result: "Interior" },
  { min: 16, max: 55,  result: "Land" },
  { min: 56, max: 80,  result: "Liquid" },
  { min: 81, max: 100, result: "Air" },
];

export const SCALE = [
  { min: 1,  max: 3,   result: "Minuscule (bug-sized)" },
  { min: 4,  max: 10,  result: "Tiny (rodent-sized)" },
  { min: 11, max: 25,  result: "Small (dog-sized)" },
  { min: 26, max: 60,  result: "Medium (person-sized)" },
  { min: 61, max: 90,  result: "Large (vehicle-sized)" },
  { min: 91, max: 99,  result: "Huge (whale-sized)" },
  { min: 100,max: 100, result: "Ultra-scale (roll on ultra table)" },
];

// Basic form tables vary by environment
export const BASIC_FORM_SPACE = [
  { min: 1,  max: 5,   result: "Amoeba / pseudopods" },
  { min: 6,  max: 20,  result: "Amorphous / elemental" },
  { min: 21, max: 30,  result: "Avian / winged" },
  { min: 31, max: 32,  result: "Beast / mammal" },
  { min: 33, max: 34,  result: "Crustacean / shelled" },
  { min: 35, max: 37,  result: "Fish / torpedo-shaped" },
  { min: 38, max: 39,  result: "Humanoid / bipedal" },
  { min: 40, max: 41,  result: "Insectoid / exoskeletal" },
  { min: 42, max: 60,  result: "Jellyfish / gasbag" },
  { min: 61, max: 62,  result: "Lizard / reptilian" },
  { min: 63, max: 67,  result: "Octopoid / tentacled" },
  { min: 68, max: 72,  result: "Plant / fungus" },
  { min: 73, max: 82,  result: "Ray / flat-bodied" },
  { min: 83, max: 84,  result: "Snake / eel" },
  { min: 85, max: 86,  result: "Spider / web-weaver" },
  { min: 87, max: 88,  result: "Starfish / symmetrical" },
  { min: 89, max: 90,  result: "Worm / slug / larva" },
  { min: 91, max: 100, result: "Roll twice" },
];

export const BASIC_FORM_LAND = [
  { min: 1,  max: 2,   result: "Amoeba / pseudopods" },
  { min: 3,  max: 5,   result: "Amorphous / elemental" },
  { min: 6,  max: 10,  result: "Avian / winged" },
  { min: 11, max: 25,  result: "Beast / mammal" },
  { min: 26, max: 32,  result: "Crustacean / shelled" },
  { min: 33, max: 34,  result: "Fish / torpedo-shaped" },
  { min: 35, max: 39,  result: "Humanoid / bipedal" },
  { min: 40, max: 49,  result: "Insectoid / exoskeletal" },
  { min: 50, max: 51,  result: "Jellyfish / gasbag" },
  { min: 52, max: 58,  result: "Lizard / reptilian" },
  { min: 59, max: 60,  result: "Octopoid / tentacled" },
  { min: 61, max: 65,  result: "Plant / fungus" },
  { min: 66, max: 67,  result: "Ray / flat-bodied" },
  { min: 68, max: 74,  result: "Snake / eel" },
  { min: 75, max: 81,  result: "Spider / web-weaver" },
  { min: 82, max: 83,  result: "Starfish / symmetrical" },
  { min: 84, max: 90,  result: "Worm / slug / larva" },
  { min: 91, max: 100, result: "Roll twice" },
];

export const BASIC_FORM_LIQUID = [
  { min: 1,  max: 5,   result: "Amoeba / pseudopods" },
  { min: 6,  max: 8,   result: "Amorphous / elemental" },
  { min: 9,  max: 11,  result: "Avian / winged" },
  { min: 12, max: 17,  result: "Beast / mammal" },
  { min: 18, max: 24,  result: "Crustacean / shelled" },
  { min: 25, max: 39,  result: "Fish / torpedo-shaped" },
  { min: 40, max: 42,  result: "Humanoid / bipedal" },
  { min: 43, max: 45,  result: "Insectoid / exoskeletal" },
  { min: 46, max: 53,  result: "Jellyfish / gasbag" },
  { min: 54, max: 56,  result: "Lizard / reptilian" },
  { min: 57, max: 63,  result: "Octopoid / tentacled" },
  { min: 64, max: 68,  result: "Plant / fungus" },
  { min: 69, max: 75,  result: "Ray / flat-bodied" },
  { min: 76, max: 80,  result: "Snake / eel" },
  { min: 81, max: 82,  result: "Spider / web-weaver" },
  { min: 83, max: 87,  result: "Starfish / symmetrical" },
  { min: 88, max: 90,  result: "Worm / slug / larva" },
  { min: 91, max: 100, result: "Roll twice" },
];

export const BASIC_FORM_AIR = [
  { min: 1,  max: 2,   result: "Amoeba / pseudopods" },
  { min: 3,  max: 12,  result: "Amorphous / elemental" },
  { min: 13, max: 37,  result: "Avian / winged" },
  { min: 38, max: 40,  result: "Beast / mammal" },
  { min: 41, max: 42,  result: "Crustacean / shelled" },
  { min: 43, max: 47,  result: "Fish / torpedo-shaped" },
  { min: 48, max: 49,  result: "Humanoid / bipedal" },
  { min: 50, max: 51,  result: "Insectoid / exoskeletal" },
  { min: 52, max: 66,  result: "Jellyfish / gasbag" },
  { min: 67, max: 68,  result: "Lizard / reptilian" },
  { min: 69, max: 70,  result: "Octopoid / tentacled" },
  { min: 71, max: 72,  result: "Plant / fungus" },
  { min: 73, max: 82,  result: "Ray / flat-bodied" },
  { min: 83, max: 84,  result: "Snake / eel" },
  { min: 85, max: 86,  result: "Spider / web-weaver" },
  { min: 87, max: 88,  result: "Starfish / symmetrical" },
  { min: 89, max: 90,  result: "Worm / slug / larva" },
  { min: 91, max: 100, result: "Roll twice" },
];

export const BASIC_FORM_INTERIOR = BASIC_FORM_LAND; // Close enough for interior spaces

export const FIRST_LOOK = [
  { min: 1,  max: 2,   result: "Antennae or sensory organs" },
  { min: 3,  max: 4,   result: "Armored" },
  { min: 5,  max: 6,   result: "Beautiful" },
  { min: 7,  max: 8,   result: "Biotech" },
  { min: 9,  max: 10,  result: "Bony or gaunt" },
  { min: 11, max: 12,  result: "Brutish or muscled" },
  { min: 13, max: 14,  result: "Camouflaged" },
  { min: 15, max: 16,  result: "Claws or talons" },
  { min: 17, max: 18,  result: "Compound eyes" },
  { min: 19, max: 20,  result: "Comprised of many creatures" },
  { min: 21, max: 22,  result: "Corrupted" },
  { min: 23, max: 24,  result: "Crystalline" },
  { min: 25, max: 26,  result: "Dead or undead" },
  { min: 27, max: 28,  result: "Distinctive markings" },
  { min: 29, max: 30,  result: "Distinctive smell" },
  { min: 31, max: 32,  result: "Distinctive sound" },
  { min: 33, max: 34,  result: "Dripping mucus" },
  { min: 35, max: 36,  result: "Elongated neck" },
  { min: 37, max: 38,  result: "Energy emissions" },
  { min: 39, max: 40,  result: "Extra limbs" },
  { min: 41, max: 42,  result: "Faceless or inexpressive" },
  { min: 43, max: 44,  result: "Fangs or rows of teeth" },
  { min: 45, max: 46,  result: "Feathered" },
  { min: 47, max: 48,  result: "Hidden symbiote" },
  { min: 49, max: 50,  result: "Hive mind" },
  { min: 51, max: 52,  result: "Graceful" },
  { min: 53, max: 54,  result: "Hideous" },
  { min: 55, max: 56,  result: "Hooded or crested" },
  { min: 57, max: 58,  result: "Immobile or trapped" },
  { min: 59, max: 60,  result: "Injured or scarred" },
  { min: 61, max: 62,  result: "Iridescent" },
  { min: 63, max: 64,  result: "Long-limbed" },
  { min: 65, max: 66,  result: "Luminescent" },
  { min: 67, max: 68,  result: "Mandibles or pincers" },
  { min: 69, max: 70,  result: "Many-eyed" },
  { min: 71, max: 72,  result: "Mineral or metallic" },
  { min: 73, max: 74,  result: "Multi-jointed" },
  { min: 75, max: 76,  result: "Multi-segmented body" },
  { min: 77, max: 78,  result: "Ornamented or colorful" },
  { min: 79, max: 80,  result: "Oversized mouth" },
  { min: 81, max: 82,  result: "Prominent tail" },
  { min: 83, max: 84,  result: "Prominent wings or fins" },
  { min: 85, max: 86,  result: "Ridges or plates" },
  { min: 87, max: 88,  result: "Scaled" },
  { min: 89, max: 90,  result: "Single eye or oversized eyes" },
  { min: 91, max: 92,  result: "Spikes or spines" },
  { min: 93, max: 94,  result: "Stinger or barbs" },
  { min: 95, max: 96,  result: "Tentacles or tendrils" },
  { min: 97, max: 98,  result: "Translucent" },
  { min: 99, max: 100, result: "Visible symbiote" },
];

export const BEHAVIOR = [
  { min: 1,  max: 5,   result: "Ambusher" },
  { min: 6,  max: 10,  result: "Apex predator" },
  { min: 11, max: 14,  result: "Builder" },
  { min: 15, max: 19,  result: "Camouflager" },
  { min: 20, max: 24,  result: "Forager" },
  { min: 25, max: 29,  result: "Grazer" },
  { min: 30, max: 33,  result: "Herder" },
  { min: 34, max: 37,  result: "Hibernator" },
  { min: 38, max: 41,  result: "Hoarder" },
  { min: 42, max: 46,  result: "Hunter" },
  { min: 47, max: 51,  result: "Lurer" },
  { min: 52, max: 55,  result: "Migratory" },
  { min: 56, max: 60,  result: "Mimic" },
  { min: 61, max: 65,  result: "Nester" },
  { min: 66, max: 70,  result: "Pack hunter" },
  { min: 71, max: 75,  result: "Prey" },
  { min: 76, max: 80,  result: "Protector" },
  { min: 81, max: 85,  result: "Scavenger" },
  { min: 86, max: 90,  result: "Tracker" },
  { min: 91, max: 95,  result: "Trapper" },
  { min: 96, max: 100, result: "Roll twice" },
];

export const REVEALED_ASPECT = [
  { min: 1,  max: 2,   result: "Alternative movement" },
  { min: 3,  max: 4,   result: "Alternative senses" },
  { min: 5,  max: 6,   result: "Alternative environment" },
  { min: 7,  max: 8,   result: "Burrower" },
  { min: 9,  max: 10,  result: "Chameleon" },
  { min: 11, max: 12,  result: "Clever" },
  { min: 13, max: 14,  result: "Consumes energy" },
  { min: 15, max: 16,  result: "Consumes inorganic matter" },
  { min: 17, max: 18,  result: "Controlled or puppeteered" },
  { min: 19, max: 20,  result: "Controls lesser creatures" },
  { min: 21, max: 22,  result: "Corrosive excretion" },
  { min: 23, max: 24,  result: "Crusher or constrictor" },
  { min: 25, max: 26,  result: "Egg sac or carried offspring" },
  { min: 27, max: 28,  result: "Electric shock" },
  { min: 29, max: 30,  result: "Electromagnetic pulse" },
  { min: 31, max: 32,  result: "Energy breath" },
  { min: 33, max: 34,  result: "Energy manipulation" },
  { min: 35, max: 36,  result: "Engineered biology" },
  { min: 37, max: 38,  result: "Enhanced senses" },
  { min: 39, max: 40,  result: "Enhanced strength" },
  { min: 41, max: 42,  result: "Entangling secretion" },
  { min: 43, max: 44,  result: "Extradimensional" },
  { min: 45, max: 46,  result: "Hallucinogen secretion" },
  { min: 47, max: 48,  result: "Fungal growth" },
  { min: 49, max: 50,  result: "Fur, hair, or filaments" },
  { min: 51, max: 52,  result: "Illusionary" },
  { min: 53, max: 54,  result: "Infectious" },
  { min: 55, max: 56,  result: "Infested with parasites" },
  { min: 57, max: 58,  result: "Intimidating threat display" },
  { min: 59, max: 60,  result: "Limited sense" },
  { min: 61, max: 62,  result: "Magnetic" },
  { min: 63, max: 64,  result: "Mental influence or control" },
  { min: 65, max: 66,  result: "Metamorphic" },
  { min: 67, max: 68,  result: "Noxious cloud or spores" },
  { min: 69, max: 70,  result: "Paralytic toxin" },
  { min: 71, max: 72,  result: "Parasitic" },
  { min: 73, max: 74,  result: "Pheromones" },
  { min: 75, max: 76,  result: "Poisonous" },
  { min: 77, max: 78,  result: "Powerful bite" },
  { min: 79, max: 80,  result: "Proboscis or inner jaw" },
  { min: 81, max: 82,  result: "Projectile attack" },
  { min: 83, max: 84,  result: "Radioactive" },
  { min: 85, max: 86,  result: "Regeneration" },
  { min: 87, max: 88,  result: "Replication" },
  { min: 89, max: 90,  result: "Sacrificial defense" },
  { min: 91, max: 92,  result: "Shapechanger" },
  { min: 93, max: 94,  result: "Telekinetic" },
  { min: 95, max: 96,  result: "Teleportation" },
  { min: 97, max: 98,  result: "Territorial" },
  { min: 99, max: 100, result: "Toxic spew" },
];
