/**
 * src/oracles/tables/factions.js
 * Source: Starforged Reference Guide pp.72-79
 */

export const TYPE = [
  { min: 1,  max: 40,  result: "Dominion — Governing power" },
  { min: 41, max: 70,  result: "Guild — Organization of specialists" },
  { min: 71, max: 100, result: "Fringe Group — Band of outlaws, outcasts, or rogues" },
];

export const INFLUENCE = [
  { min: 1,  max: 10,  result: "Forsaken — Banished or forgotten" },
  { min: 11, max: 30,  result: "Isolated — Limited influence in a remote location" },
  { min: 31, max: 50,  result: "Localized — Marginal influence in a single sector" },
  { min: 51, max: 70,  result: "Established — Strong influence in a single sector" },
  { min: 71, max: 85,  result: "Notable — Dispersed influence across a few sectors" },
  { min: 86, max: 95,  result: "Dominant — Far-reaching influence across many sectors" },
  { min: 96, max: 100, result: "Inescapable — Pervasive influence across inhabited space" },
];

export const DOMINION = [
  { min: 1,  max: 5,   result: "Agriculture" },    { min: 6,  max: 9,   result: "Artistry" },
  { min: 10, max: 14,  result: "Commerce" },        { min: 15, max: 18,  result: "Conquest" },
  { min: 19, max: 22,  result: "Construction" },    { min: 23, max: 26,  result: "Diplomacy" },
  { min: 27, max: 30,  result: "Education" },       { min: 31, max: 34,  result: "Environmentalism" },
  { min: 35, max: 38,  result: "Exploration" },     { min: 39, max: 42,  result: "Faith" },
  { min: 43, max: 46,  result: "History" },         { min: 47, max: 50,  result: "Honor" },
  { min: 51, max: 55,  result: "Industry" },        { min: 56, max: 59,  result: "Isolationism" },
  { min: 60, max: 63,  result: "Law" },             { min: 64, max: 67,  result: "Mysticism" },
  { min: 68, max: 71,  result: "Pacifism" },        { min: 72, max: 75,  result: "Prophecy" },
  { min: 76, max: 79,  result: "Science" },         { min: 80, max: 83,  result: "Secrecy" },
  { min: 84, max: 87,  result: "Technology" },      { min: 88, max: 91,  result: "Treachery" },
  { min: 92, max: 96,  result: "Warfare" },         { min: 97, max: 100, result: "Wealth" },
];

export const DOMINION_LEADERSHIP = [
  { min: 1,  max: 5,   result: "Anarchist" },
  { min: 6,  max: 15,  result: "Disputed leadership" },
  { min: 16, max: 30,  result: "Authoritarian dictatorship" },
  { min: 31, max: 45,  result: "Oligarchical elite" },
  { min: 46, max: 60,  result: "Dynastic lineage" },
  { min: 61, max: 70,  result: "Fated or prophesied leader" },
  { min: 71, max: 80,  result: "Clan chiefs or elders" },
  { min: 81, max: 90,  result: "Elected representatives" },
  { min: 91, max: 95,  result: "Machine intelligence" },
  { min: 96, max: 100, result: "Varied / decentralized" },
];

export const GUILD = [
  { min: 1,  max: 5,   result: "Assassins" },     { min: 6,  max: 10,  result: "Bounty hunters" },
  { min: 11, max: 15,  result: "Couriers" },       { min: 16, max: 20,  result: "Courtesans" },
  { min: 21, max: 25,  result: "Engineers" },      { min: 26, max: 30,  result: "Healers" },
  { min: 31, max: 40,  result: "Industrialists" }, { min: 41, max: 50,  result: "Mercenaries" },
  { min: 51, max: 60,  result: "Merchants" },      { min: 61, max: 65,  result: "Mystics" },
  { min: 66, max: 75,  result: "Navigators" },     { min: 76, max: 80,  result: "Peacekeepers" },
  { min: 81, max: 85,  result: "Researchers" },    { min: 86, max: 90,  result: "Spies" },
  { min: 91, max: 100, result: "Roll twice" },
];

export const FRINGE_GROUP = [
  { min: 1,  max: 5,   result: "Cultists" },    { min: 6,  max: 15,  result: "Exiles" },
  { min: 16, max: 25,  result: "Gangsters" },   { min: 26, max: 35,  result: "Hackers" },
  { min: 36, max: 40,  result: "Monster hunters" }, { min: 41, max: 50, result: "Pirates" },
  { min: 51, max: 60,  result: "Raiders" },     { min: 61, max: 70,  result: "Rebels" },
  { min: 71, max: 75,  result: "Rogue AI" },    { min: 76, max: 85,  result: "Scavengers" },
  { min: 86, max: 95,  result: "Smugglers" },   { min: 96, max: 100, result: "Roll twice" },
];

export const PROJECTS = [
  { min: 1,  max: 3,   result: "Broaden scope of the faction to include a new focus" },
  { min: 4,  max: 6,   result: "Build or secure a powerful device" },
  { min: 7,  max: 9,   result: "Consolidate control of a valuable commodity" },
  { min: 10, max: 12,  result: "Destroy or defeat a rival" },
  { min: 13, max: 15,  result: "Disrupt the operations of a rival" },
  { min: 16, max: 18,  result: "Escape the control of another faction or power" },
  { min: 19, max: 21,  result: "Establish a monument or memorial" },
  { min: 22, max: 24,  result: "Establish a safe refuge or headquarters" },
  { min: 25, max: 27,  result: "Expand operations to a new location or sector" },
  { min: 28, max: 30,  result: "Form an alliance" },
  { min: 31, max: 33,  result: "Fulfill a prophecy" },
  { min: 34, max: 36,  result: "Give aid to a faction" },
  { min: 37, max: 39,  result: "Harness unnatural or forbidden power" },
  { min: 40, max: 42,  result: "Hunt down a rogue asset" },
  { min: 43, max: 45,  result: "Incite conflict among rivals" },
  { min: 46, max: 48,  result: "Negotiate an agreement" },
  { min: 49, max: 51,  result: "Obtain a needed commodity" },
  { min: 52, max: 54,  result: "Obtain an important cultural artifact" },
  { min: 55, max: 57,  result: "Obtain crucial data or information" },
  { min: 58, max: 60,  result: "Obtain incriminating information about a rival" },
  { min: 61, max: 63,  result: "Prevent a prophecy" },
  { min: 64, max: 66,  result: "Put down an internal revolt or rebellion" },
  { min: 67, max: 69,  result: "Repay a debt" },
  { min: 70, max: 72,  result: "Rescue or recover a group or asset" },
  { min: 73, max: 75,  result: "Research an innovation" },
  { min: 76, max: 78,  result: "Resolve a conflict with another faction" },
  { min: 79, max: 81,  result: "Reunite splintered elements of the faction" },
  { min: 82, max: 84,  result: "Seize a powerful artifact or valuable treasure" },
  { min: 85, max: 87,  result: "Seize rival territory or operations" },
  { min: 88, max: 90,  result: "Subsume another faction" },
  { min: 91, max: 93,  result: "Transport a valued asset" },
  { min: 94, max: 96,  result: "Usurp leadership within a rival faction" },
  { min: 97, max: 100, result: "Action + Theme", ref: "action_theme" },
];

export const RELATIONSHIPS = [
  { min: 1,  max: 4,   result: "Antagonistic towards" },
  { min: 5,  max: 8,   result: "Apathetic or unaware of" },
  { min: 9,  max: 11,  result: "Betrayed by" },
  { min: 12, max: 14,  result: "Broke faith with" },
  { min: 15, max: 18,  result: "Distrustful of" },
  { min: 19, max: 22,  result: "Does business with" },
  { min: 23, max: 25,  result: "Extorted by" },
  { min: 26, max: 29,  result: "Holds contempt for" },
  { min: 30, max: 33,  result: "Holds leverage over" },
  { min: 34, max: 36,  result: "In control of" },
  { min: 37, max: 40,  result: "Maneuvering against" },
  { min: 41, max: 44,  result: "Needs aid from" },
  { min: 45, max: 47,  result: "Negotiating with" },
  { min: 48, max: 51,  result: "Open alliance with" },
  { min: 52, max: 54,  result: "Owes a debt to" },
  { min: 55, max: 58,  result: "Shares a rivalry with" },
  { min: 59, max: 61,  result: "Shares power with" },
  { min: 62, max: 64,  result: "Shows respect for" },
  { min: 65, max: 67,  result: "Splintered from" },
  { min: 68, max: 70,  result: "Subordinate to" },
  { min: 71, max: 74,  result: "Supplied with resources by" },
  { min: 75, max: 78,  result: "Supplies resources to" },
  { min: 79, max: 81,  result: "Temporary alliance with" },
  { min: 82, max: 85,  result: "Tolerates" },
  { min: 86, max: 89,  result: "Trades favors with" },
  { min: 90, max: 92,  result: "Unjustly accused by" },
  { min: 93, max: 96,  result: "Warring with" },
  { min: 97, max: 100, result: "Roll twice" },
];

export const QUIRKS = [
  { min: 1,  max: 3,   result: "Ancient or coded language" },
  { min: 4,  max: 6,   result: "Animal or creature motif used as a faction symbol" },
  { min: 7,  max: 9,   result: "Banishes the disloyal" },
  { min: 10, max: 12,  result: "Body augmentations are respected and valued" },
  { min: 13, max: 15,  result: "Body ornamentations signify castes or roles" },
  { min: 16, max: 18,  result: "Conceals individual identity" },
  { min: 19, max: 21,  result: "Dependent on an addictive substance" },
  { min: 22, max: 24,  result: "Distinctive or elaborate clothing" },
  { min: 25, max: 27,  result: "Elite soldiers provide defense or serve as bodyguards" },
  { min: 28, max: 30,  result: "Favors a signature weapon" },
  { min: 31, max: 33,  result: "Guided by superstition or prophecy" },
  { min: 34, max: 36,  result: "Heavily stratified social structure" },
  { min: 37, max: 39,  result: "Hoards precursor artifacts" },
  { min: 40, max: 42,  result: "Honors the fallen through unusual death rites" },
  { min: 43, max: 45,  result: "Idolizes a long-dead founder or martyr" },
  { min: 46, max: 48,  result: "Keeps exhaustive records or archives" },
  { min: 49, max: 51,  result: "Lives off-planet in spaceborne fleets" },
  { min: 52, max: 54,  result: "Members take a new name when joining the faction" },
  { min: 55, max: 57,  result: "Nomadic people and mobile operations" },
  { min: 58, max: 60,  result: "Operates under strict codes or laws" },
  { min: 61, max: 63,  result: "Recognizes others through a distinctive greeting or gesture" },
  { min: 64, max: 66,  result: "Reliant on machine intelligence" },
  { min: 67, max: 69,  result: "Resolves disputes through formal duels" },
  { min: 70, max: 72,  result: "Rites of adulthood or ascension" },
  { min: 73, max: 75,  result: "Shuns or distrusts machine intelligence" },
  { min: 76, max: 78,  result: "Starships share a distinctive and recognizable profile" },
  { min: 79, max: 81,  result: "Suspicious of outsiders" },
  { min: 82, max: 84,  result: "Symbiotic relationship with a specific type of creature" },
  { min: 85, max: 87,  result: "Trades in a unique currency or commodity" },
  { min: 88, max: 90,  result: "Trains in a demanding physical discipline or martial art" },
  { min: 91, max: 93,  result: "Wields unnatural abilities or strange technologies" },
  { min: 94, max: 96,  result: "Work or environment causes mutations" },
  { min: 97, max: 100, result: "Action + Theme", ref: "action_theme" },
];

export const RUMORS = [
  { min: 1,  max: 3,   result: "Caught in the crossfire of feuding factions" },
  { min: 4,  max: 6,   result: "Colluding with a criminal enterprise" },
  { min: 7,  max: 9,   result: "Corrupted by a dangerous power" },
  { min: 10, max: 12,  result: "Critical resource is in short supply" },
  { min: 13, max: 15,  result: "Defenses are overextended" },
  { min: 16, max: 18,  result: "Developing revolutionary technology" },
  { min: 19, max: 21,  result: "Digital systems are corrupted or infiltrated" },
  { min: 22, max: 24,  result: "Heavily in debt" },
  { min: 25, max: 27,  result: "Hit hard by a recent attack or calamity" },
  { min: 28, max: 30,  result: "Holds a powerful artifact" },
  { min: 31, max: 33,  result: "Holds incriminating information against a leader or faction" },
  { min: 34, max: 36,  result: "Hoarding a valuable commodity" },
  { min: 37, max: 39,  result: "Infiltrated by a rival faction" },
  { min: 40, max: 42,  result: "Knows the location of a fabled treasure or lost technology" },
  { min: 43, max: 45,  result: "Leaders are haunted by a dark prophecy" },
  { min: 46, max: 48,  result: "Leaders are incompetent" },
  { min: 49, max: 51,  result: "Leaders are puppets of another power or faction" },
  { min: 52, max: 54,  result: "Lesser members of the leadership are plotting a coup" },
  { min: 55, max: 57,  result: "New belief or religion is creating a schism among members" },
  { min: 58, max: 60,  result: "Operations are a false front for their true purpose" },
  { min: 61, max: 63,  result: "Overdependence on a failing or vulnerable technology" },
  { min: 64, max: 66,  result: "Plagued by infighting and low morale" },
  { min: 67, max: 69,  result: "Plotting to betray an allied faction" },
  { min: 70, max: 72,  result: "Preparing a major offensive or operation" },
  { min: 73, max: 75,  result: "Pulling the strings of a leader or faction" },
  { min: 76, max: 78,  result: "Recently acquired an unexpected fortune" },
  { min: 79, max: 81,  result: "Secretly supporting a reviled faction" },
  { min: 82, max: 84,  result: "Sheltering an infamous or dangerous fugitive" },
  { min: 85, max: 87,  result: "Suffered destructive sabotage from within" },
  { min: 88, max: 90,  result: "Suffering a shortage of key workers or personnel" },
  { min: 91, max: 93,  result: "Uprising or revolt is brewing from within" },
  { min: 94, max: 96,  result: "Vulnerable to attack or aggression" },
  { min: 97, max: 100, result: "Action + Theme", ref: "action_theme" },
];

export const NAME_TEMPLATE = [
  { min: 1,  max: 40,  result: "[Legacy] [Affiliation]" },
  { min: 41, max: 55,  result: "[Legacy] [Identity]" },
  { min: 56, max: 70,  result: "[Identity] of the [Legacy] [Affiliation]" },
  { min: 71, max: 100, result: "[Affiliation] of the [Legacy] [Identity]" },
];

export const NAME_LEGACY = [
  { min: 1,  max: 2,   result: "Ancient" },   { min: 3,  max: 4,   result: "Ashen" },
  { min: 5,  max: 6,   result: "Awakened" },  { min: 7,  max: 8,   result: "Azure" },
  { min: 9,  max: 10,  result: "Blessed" },   { min: 11, max: 12,  result: "Bloody" },
  { min: 13, max: 14,  result: "Broken" },    { min: 15, max: 16,  result: "Ceaseless" },
  { min: 17, max: 18,  result: "Crimson" },   { min: 19, max: 20,  result: "Cursed" },
  { min: 21, max: 22,  result: "Dawning" },   { min: 23, max: 24,  result: "Dissident" },
  { min: 25, max: 26,  result: "Ebon" },      { min: 27, max: 28,  result: "Elder" },
  { min: 29, max: 30,  result: "Enduring" },  { min: 31, max: 32,  result: "Enlightened" },
  { min: 33, max: 34,  result: "Exalted" },   { min: 35, max: 36,  result: "Fallen" },
  { min: 37, max: 38,  result: "Fated" },     { min: 39, max: 40,  result: "First" },
  { min: 41, max: 42,  result: "Forgotten" }, { min: 43, max: 44,  result: "Forsaken" },
  { min: 45, max: 46,  result: "Gloaming" },  { min: 47, max: 48,  result: "Golden" },
  { min: 49, max: 50,  result: "Hidden" },    { min: 51, max: 52,  result: "Infernal" },
  { min: 53, max: 54,  result: "Infinite" },  { min: 55, max: 56,  result: "Iron" },
  { min: 57, max: 58,  result: "Kindred" },   { min: 59, max: 60,  result: "Obsidian" },
  { min: 61, max: 62,  result: "Radiant" },   { min: 63, max: 64,  result: "Risen" },
  { min: 65, max: 66,  result: "Sacred" },    { min: 67, max: 68,  result: "Sapphire" },
  { min: 69, max: 70,  result: "Scarlet" },   { min: 71, max: 72,  result: "Serene" },
  { min: 73, max: 74,  result: "Shattered" }, { min: 75, max: 76,  result: "Shining" },
  { min: 77, max: 78,  result: "Silent" },    { min: 79, max: 80,  result: "Silver" },
  { min: 81, max: 82,  result: "Sovereign" }, { min: 83, max: 84,  result: "Stellar" },
  { min: 85, max: 86,  result: "Sundered" },  { min: 87, max: 88,  result: "Supreme" },
  { min: 89, max: 90,  result: "Undying" },   { min: 91, max: 92,  result: "Unified" },
  { min: 93, max: 94,  result: "United" },    { min: 95, max: 96,  result: "Universal" },
  { min: 97, max: 98,  result: "Veiled" },    { min: 99, max: 100, result: "Wandering" },
];

export const NAME_AFFILIATION = [
  { min: 1,  max: 4,   result: "Accord" },      { min: 5,  max: 8,   result: "Alliance" },
  { min: 9,  max: 12,  result: "Ascendancy" },  { min: 13, max: 16,  result: "Circle" },
  { min: 17, max: 20,  result: "Coalition" },   { min: 21, max: 24,  result: "Collective" },
  { min: 25, max: 28,  result: "Commonwealth" },{ min: 29, max: 32,  result: "Confederation" },
  { min: 33, max: 36,  result: "Consortium" },  { min: 37, max: 40,  result: "Council" },
  { min: 41, max: 44,  result: "Court" },       { min: 45, max: 48,  result: "Covenant" },
  { min: 49, max: 52,  result: "Dominion" },    { min: 53, max: 56,  result: "Empire" },
  { min: 57, max: 60,  result: "Federation" },  { min: 61, max: 64,  result: "Imperium" },
  { min: 65, max: 68,  result: "League" },      { min: 69, max: 72,  result: "Legion" },
  { min: 73, max: 76,  result: "Order" },       { min: 77, max: 80,  result: "Pact" },
  { min: 81, max: 84,  result: "Regiment" },    { min: 85, max: 88,  result: "Republic" },
  { min: 89, max: 92,  result: "Sphere" },      { min: 93, max: 96,  result: "Syndicate" },
  { min: 97, max: 100, result: "Union" },
];

export const NAME_IDENTITY = [
  { min: 1,  max: 2,   result: "Blades" },    { min: 3,  max: 4,   result: "Builders" },
  { min: 5,  max: 6,   result: "Daggers" },   { min: 7,  max: 8,   result: "Defenders" },
  { min: 9,  max: 10,  result: "Disciples" }, { min: 11, max: 12,  result: "Domains" },
  { min: 13, max: 14,  result: "Drifters" },  { min: 15, max: 16,  result: "Embers" },
  { min: 17, max: 18,  result: "Flames" },    { min: 19, max: 20,  result: "Fleet" },
  { min: 21, max: 22,  result: "Guardians" }, { min: 23, max: 24,  result: "Hammers" },
  { min: 25, max: 26,  result: "Harbingers" },{ min: 27, max: 28,  result: "Heralds" },
  { min: 29, max: 30,  result: "Hounds" },    { min: 31, max: 32,  result: "Hunters" },
  { min: 33, max: 34,  result: "Jackals" },   { min: 35, max: 36,  result: "Keepers" },
  { min: 37, max: 38,  result: "Knights" },   { min: 39, max: 40,  result: "Menders" },
  { min: 41, max: 42,  result: "Outcasts" },  { min: 43, max: 44,  result: "Phantoms" },
  { min: 45, max: 46,  result: "Planets" },   { min: 47, max: 48,  result: "Raiders" },
  { min: 49, max: 50,  result: "Ravens" },    { min: 51, max: 52,  result: "Realms" },
  { min: 53, max: 54,  result: "Reavers" },   { min: 55, max: 56,  result: "Relics" },
  { min: 57, max: 58,  result: "Seekers" },   { min: 59, max: 60,  result: "Sentinels" },
  { min: 61, max: 62,  result: "Serpents" },  { min: 63, max: 64,  result: "Servants" },
  { min: 65, max: 66,  result: "Shadows" },   { min: 67, max: 68,  result: "Shards" },
  { min: 69, max: 70,  result: "Skulls" },    { min: 71, max: 72,  result: "Souls" },
  { min: 73, max: 74,  result: "Specters" },  { min: 75, max: 76,  result: "Stars" },
  { min: 77, max: 78,  result: "Suns" },      { min: 79, max: 80,  result: "Swarm" },
  { min: 81, max: 82,  result: "Swords" },    { min: 83, max: 84,  result: "Talons" },
  { min: 85, max: 86,  result: "Vanguards" }, { min: 87, max: 88,  result: "Wardens" },
  { min: 89, max: 90,  result: "Watchers" },  { min: 91, max: 92,  result: "Wolves" },
  { min: 93, max: 94,  result: "Worlds" },    { min: 95, max: 96,  result: "Wraiths" },
  { min: 97, max: 98,  result: "Wreckers" },  { min: 99, max: 100, result: "Wrights" },
];
