/**
 * src/oracles/tables/planets.js
 * Source: Starforged Reference Guide pp.38-53
 */

export const PLANET_TYPE = [
  { min: 1,  max: 15,  result: "Desert World" },
  { min: 16, max: 30,  result: "Furnace World" },
  { min: 31, max: 35,  result: "Grave World" },
  { min: 36, max: 50,  result: "Ice World" },
  { min: 51, max: 65,  result: "Jovian World" },
  { min: 66, max: 70,  result: "Jungle World" },
  { min: 71, max: 75,  result: "Ocean World" },
  { min: 76, max: 90,  result: "Rocky World" },
  { min: 91, max: 92,  result: "Shattered World" },
  { min: 93, max: 98,  result: "Tainted World" },
  { min: 99, max: 100, result: "Vital World" },
];

export const PLANETSIDE_PERIL_LIFEBEARING = [
  { min: 1,  max: 3,   result: "Corrupted or mutated lifeform" },
  { min: 4,  max: 6,   result: "Signs of a lifeform's power or cunning" },
  { min: 7,  max: 9,   result: "Hazardous plant life or malignant spores" },
  { min: 10, max: 12,  result: "Lifeform hunts for prey" },
  { min: 13, max: 15,  result: "Lifeform lairs here" },
  { min: 16, max: 18,  result: "Lifeforms guided by a greater threat" },
  { min: 19, max: 21,  result: "Lifeforms spooked or stampeding" },
  { min: 22, max: 24,  result: "Threatening lifeform draws near" },
  { min: 25, max: 27,  result: "Life is revealed or takes an unexpected form" },
  { min: 28, max: 30,  result: "Blocked or impassable path" },
  { min: 31, max: 33,  result: "Corrosive substance or environment" },
  { min: 34, max: 36,  result: "Disturbing remains or evidence of death" },
  { min: 37, max: 39,  result: "Drastic environmental change" },
  { min: 40, max: 42,  result: "Enemy holds this area" },
  { min: 43, max: 45,  result: "Entangling or engulfing hazard" },
  { min: 46, max: 48,  result: "Equipment fails or malfunctions" },
  { min: 49, max: 51,  result: "Guarded or patrolled path" },
  { min: 52, max: 54,  result: "Led astray" },
  { min: 55, max: 57,  result: "Lost the path" },
  { min: 58, max: 60,  result: "Meteorites fall from the sky" },
  { min: 61, max: 63,  result: "Irradiated area or object" },
  { min: 64, max: 66,  result: "Realization that something was left behind" },
  { min: 67, max: 69,  result: "Seismic or volcanic upheaval" },
  { min: 70, max: 72,  result: "Signs of a lurking or trailing foe" },
  { min: 73, max: 75,  result: "Storm or atmospheric disruption" },
  { min: 76, max: 78,  result: "Toxic or sickening environment" },
  { min: 79, max: 81,  result: "Trap or alarm" },
  { min: 82, max: 84,  result: "Treacherous or arduous path" },
  { min: 85, max: 87,  result: "Troubling visions or apparitions" },
  { min: 88, max: 90,  result: "Visibility hindered by atmospheric effects" },
  { min: 91, max: 93,  result: "Worrying arrival of a ship or vehicle" },
  { min: 94, max: 96,  result: "Wreckage or ruins portend a new threat" },
  { min: 97, max: 99,  result: "Action + Theme", ref: "action_theme" },
  { min: 100,max: 100, result: "Roll twice" },
];

export const PLANETSIDE_PERIL_LIFELESS = [
  { min: 1,  max: 7,   result: "Blocked or impassable path" },
  { min: 8,  max: 14,  result: "Corrosive substance or environment" },
  { min: 15, max: 21,  result: "Disturbing remains or evidence of death" },
  { min: 22, max: 28,  result: "Drastic environmental change" },
  { min: 29, max: 35,  result: "Enemy holds this area" },
  { min: 36, max: 42,  result: "Entangling or engulfing hazard" },
  { min: 43, max: 49,  result: "Equipment fails or malfunctions" },
  { min: 50, max: 56,  result: "Guarded or patrolled path" },
  { min: 57, max: 63,  result: "Led astray" },
  { min: 64, max: 70,  result: "Lost the path" },
  { min: 71, max: 77,  result: "Meteorites fall from the sky" },
  { min: 78, max: 84,  result: "Irradiated area or object" },
  { min: 85, max: 91,  result: "Seismic or volcanic upheaval" },
  { min: 92, max: 95,  result: "Storm or atmospheric disruption" },
  { min: 96, max: 99,  result: "Action + Theme", ref: "action_theme" },
  { min: 100,max: 100, result: "Roll twice" },
];

export const PLANETSIDE_OPPORTUNITY_LIFEBEARING = [
  { min: 1,  max: 4,   result: "Clue to a lifeform's nature or vulnerabilities" },
  { min: 5,  max: 8,   result: "Friendly interaction with a benign lifeform" },
  { min: 9,  max: 12,  result: "Hunting or foraging opportunities are plentiful" },
  { min: 13, max: 16,  result: "Interesting or helpful aspect of benign creatures" },
  { min: 17, max: 20,  result: "Interesting or helpful aspect of local plant life" },
  { min: 21, max: 24,  result: "Encounter reveals unexpected benign lifeforms" },
  { min: 25, max: 28,  result: "Abandoned camp or vehicle" },
  { min: 29, max: 32,  result: "Advance warning of an environmental threat" },
  { min: 33, max: 36,  result: "Clear path through otherwise perilous terrain" },
  { min: 37, max: 40,  result: "Clue offers insight into a current quest or mystery" },
  { min: 41, max: 44,  result: "Clue to the history or nature of this place" },
  { min: 45, max: 48,  result: "Evidence that others have passed this way" },
  { min: 49, max: 52,  result: "Foe reveals themselves or tips their hand" },
  { min: 53, max: 56,  result: "Fortuitous change in the weather or atmosphere" },
  { min: 57, max: 60,  result: "Friendly traveler crosses your path" },
  { min: 61, max: 64,  result: "Helpful resource is in ample supply" },
  { min: 65, max: 68,  result: "Impressive vista offers comfort or inspiration" },
  { min: 69, max: 72,  result: "Interesting artifact or device" },
  { min: 73, max: 76,  result: "Interesting site offers opportunities for exploration" },
  { min: 77, max: 80,  result: "Moment of fellowship or inner peace" },
  { min: 81, max: 84,  result: "Opening to distract, escape, or avoid foes" },
  { min: 85, max: 88,  result: "Opening to get the drop on a foe" },
  { min: 89, max: 92,  result: "Plea for help from a potential benefactor" },
  { min: 93, max: 96,  result: "Refuge offers a place to hide, plan, or recover" },
  { min: 97, max: 100, result: "Vantage point reveals the lay of the land" },
];

export const PLANETSIDE_OPPORTUNITY_LIFELESS = [
  { min: 1,  max: 5,   result: "Encounter reveals unexpected benign lifeforms" },
  { min: 6,  max: 10,  result: "Abandoned camp or vehicle" },
  { min: 11, max: 15,  result: "Advance warning of an environmental threat" },
  { min: 16, max: 20,  result: "Clear path through otherwise perilous terrain" },
  { min: 21, max: 25,  result: "Clue offers insight into a current quest or mystery" },
  { min: 26, max: 30,  result: "Clue to the history or nature of this place" },
  { min: 31, max: 35,  result: "Evidence that others have passed this way" },
  { min: 36, max: 40,  result: "Foe reveals themselves or tips their hand" },
  { min: 41, max: 45,  result: "Fortuitous change in the weather or atmosphere" },
  { min: 46, max: 50,  result: "Friendly traveler crosses your path" },
  { min: 51, max: 55,  result: "Helpful resource is in ample supply" },
  { min: 56, max: 60,  result: "Impressive vista offers comfort or inspiration" },
  { min: 61, max: 65,  result: "Interesting artifact or device" },
  { min: 66, max: 70,  result: "Interesting site offers opportunities for exploration" },
  { min: 71, max: 75,  result: "Moment of fellowship or inner peace" },
  { min: 76, max: 80,  result: "Opening to distract, escape, or avoid foes" },
  { min: 81, max: 85,  result: "Opening to get the drop on a foe" },
  { min: 86, max: 90,  result: "Plea for help from a potential benefactor" },
  { min: 91, max: 95,  result: "Refuge offers a place to hide, plan, or recover" },
  { min: 96, max: 100, result: "Vantage point reveals the lay of the land" },
];
