/**
 * src/oracles/tables/settlements.js
 * Source: Starforged Reference Guide pp.54-57
 */

export const LOCATION = [
  { min: 1,  max: 40,  result: "Planetside" },
  { min: 41, max: 75,  result: "Orbital" },
  { min: 76, max: 100, result: "Deep Space" },
];

export const POPULATION_TERMINUS = [
  { min: 1,  max: 10,  result: "Few" },
  { min: 11, max: 25,  result: "Dozens" },
  { min: 26, max: 55,  result: "Hundreds" },
  { min: 56, max: 85,  result: "Thousands" },
  { min: 86, max: 100, result: "Tens of thousands" },
];

export const POPULATION_OUTLANDS = [
  { min: 1,  max: 15,  result: "Few" },
  { min: 16, max: 35,  result: "Dozens" },
  { min: 36, max: 65,  result: "Hundreds" },
  { min: 66, max: 90,  result: "Thousands" },
  { min: 91, max: 100, result: "Tens of thousands" },
];

export const POPULATION_EXPANSE = [
  { min: 1,  max: 20,  result: "Few" },
  { min: 21, max: 50,  result: "Dozens" },
  { min: 51, max: 80,  result: "Hundreds" },
  { min: 81, max: 95,  result: "Thousands" },
  { min: 96, max: 100, result: "Tens of thousands" },
];

export const FIRST_LOOK = [
  { min: 1,  max: 4,   result: "Beautiful architecture" },
  { min: 5,  max: 8,   result: "Built from natural materials" },
  { min: 9,  max: 14,  result: "Built from scrap metal" },
  { min: 15, max: 20,  result: "Built within repurposed ship" },
  { min: 21, max: 25,  result: "Built within terrain or asteroid" },
  { min: 26, max: 29,  result: "Elevated or multi-level construction" },
  { min: 30, max: 34,  result: "Hidden or subsurface location" },
  { min: 35, max: 37,  result: "High-tech construction" },
  { min: 38, max: 43,  result: "Industrial architecture" },
  { min: 44, max: 48,  result: "Intimidating defenses" },
  { min: 49, max: 51,  result: "Moving or transforming" },
  { min: 52, max: 56,  result: "Obvious social stratification" },
  { min: 57, max: 61,  result: "Precarious location" },
  { min: 62, max: 65,  result: "Prominent emblems or signage" },
  { min: 66, max: 71,  result: "Rustic architecture" },
  { min: 72, max: 76,  result: "Significant structural damage" },
  { min: 77, max: 80,  result: "Sprawling or dispersed structures" },
  { min: 81, max: 83,  result: "Temporary or seasonal location" },
  { min: 84, max: 87,  result: "Toxic or polluted habitat" },
  { min: 88, max: 90,  result: "Within or near Precursor Vault" },
  { min: 91, max: 100, result: "Descriptor + Focus", ref: "descriptor_focus" },
];

export const INITIAL_CONTACT = [
  { min: 1,  max: 20,  result: "Welcoming" },
  { min: 21, max: 30,  result: "Neutral / automated" },
  { min: 31, max: 50,  result: "Wary" },
  { min: 51, max: 60,  result: "Uncooperative" },
  { min: 61, max: 70,  result: "Hostile" },
  { min: 71, max: 83,  result: "Asking for help" },
  { min: 84, max: 86,  result: "In battle" },
  { min: 87, max: 89,  result: "Captured" },
  { min: 90, max: 92,  result: "Unresponsive" },
  { min: 93, max: 95,  result: "Destroyed" },
  { min: 96, max: 100, result: "Derelict", ref: "derelict_location" },
];

export const AUTHORITY = [
  { min: 1,  max: 15,  result: "None / lawless" },
  { min: 16, max: 30,  result: "Ineffectual" },
  { min: 31, max: 45,  result: "Tolerant" },
  { min: 46, max: 55,  result: "Fair" },
  { min: 56, max: 70,  result: "Unyielding" },
  { min: 71, max: 85,  result: "Corrupt" },
  { min: 86, max: 100, result: "Oppressive" },
];

export const PROJECTS = [
  { min: 1,  max: 5,   result: "Agriculture" },
  { min: 6,  max: 7,   result: "Archeology" },
  { min: 8,  max: 9,   result: "Automation" },
  { min: 10, max: 11,  result: "Black market" },
  { min: 12, max: 13,  result: "Command" },
  { min: 14, max: 17,  result: "Defense" },
  { min: 18, max: 22,  result: "Energy" },
  { min: 23, max: 25,  result: "Engineering" },
  { min: 26, max: 27,  result: "Entertainment" },
  { min: 28, max: 29,  result: "Environmentalism" },
  { min: 30, max: 31,  result: "Evacuation" },
  { min: 32, max: 33,  result: "Expansion" },
  { min: 34, max: 37,  result: "Exploration" },
  { min: 38, max: 39,  result: "Festival" },
  { min: 40, max: 41,  result: "History" },
  { min: 42, max: 43,  result: "Hunting" },
  { min: 44, max: 46,  result: "Manufacturing" },
  { min: 47, max: 49,  result: "Medical" },
  { min: 50, max: 51,  result: "Migration" },
  { min: 52, max: 57,  result: "Mining" },
  { min: 58, max: 59,  result: "Pacifism" },
  { min: 60, max: 62,  result: "Raiding" },
  { min: 63, max: 65,  result: "Research" },
  { min: 66, max: 69,  result: "Salvage" },
  { min: 70, max: 72,  result: "Secrecy" },
  { min: 73, max: 75,  result: "Shipbuilding" },
  { min: 76, max: 78,  result: "Spirituality" },
  { min: 79, max: 84,  result: "Subsistence" },
  { min: 85, max: 86,  result: "Surveillance" },
  { min: 87, max: 88,  result: "Terraforming" },
  { min: 89, max: 92,  result: "Trade" },
  { min: 93, max: 95,  result: "Warfare" },
  { min: 96, max: 100, result: "Action + Theme", ref: "action_theme" },
];

export const TROUBLE = [
  { min: 1,  max: 3,   result: "Battle for leadership" },
  { min: 4,  max: 6,   result: "Betrayal from within" },
  { min: 7,  max: 8,   result: "Caught in the crossfire" },
  { min: 9,  max: 11,  result: "Changing environment" },
  { min: 12, max: 13,  result: "Clash of cultures" },
  { min: 14, max: 17,  result: "Dangerous discovery" },
  { min: 18, max: 21,  result: "Depleted supplies" },
  { min: 22, max: 24,  result: "Deprived of a resource" },
  { min: 25, max: 28,  result: "Failing technology" },
  { min: 29, max: 32,  result: "Feuding factions" },
  { min: 33, max: 34,  result: "Ghostly visitations" },
  { min: 35, max: 38,  result: "Hazardous environment" },
  { min: 39, max: 42,  result: "Hostile lifeforms" },
  { min: 43, max: 45,  result: "Impassable route" },
  { min: 46, max: 48,  result: "Impending attack" },
  { min: 49, max: 51,  result: "Impending natural disaster" },
  { min: 52, max: 53,  result: "Invasive organisms" },
  { min: 54, max: 55,  result: "Mounting debt" },
  { min: 56, max: 57,  result: "Mysterious deaths" },
  { min: 58, max: 60,  result: "Overdue delivery" },
  { min: 61, max: 62,  result: "Plagued by sickness" },
  { min: 63, max: 65,  result: "Preyed upon by raiders" },
  { min: 66, max: 67,  result: "Revolt against leadership" },
  { min: 68, max: 69,  result: "Sabotaged technology" },
  { min: 70, max: 71,  result: "Shunned by others" },
  { min: 72, max: 74,  result: "Social strife" },
  { min: 75, max: 76,  result: "Someone is ill or injured" },
  { min: 77, max: 78,  result: "Someone is missing" },
  { min: 79, max: 80,  result: "Stolen technology or object" },
  { min: 81, max: 83,  result: "Strange phenomenon" },
  { min: 84, max: 86,  result: "Toxic waste or pollution" },
  { min: 87, max: 88,  result: "Volatile energy source" },
  { min: 89, max: 90,  result: "Vulnerable lifeforms" },
  { min: 91, max: 100, result: "Action + Theme", ref: "action_theme" },
];

export const NAMES = [
  { min: 1,   max: 1,   result: "Aegis" },     { min: 2,   max: 2,   result: "Altair" },
  { min: 3,   max: 3,   result: "Altura" },    { min: 4,   max: 4,   result: "Amity" },
  { min: 5,   max: 5,   result: "Apex" },      { min: 6,   max: 6,   result: "Apogee" },
  { min: 7,   max: 7,   result: "Argosy" },    { min: 8,   max: 8,   result: "Astra" },
  { min: 9,   max: 9,   result: "Aurora" },    { min: 10,  max: 10,  result: "Beacon" },
  { min: 11,  max: 11,  result: "Brink" },     { min: 12,  max: 12,  result: "Bulwark" },
  { min: 13,  max: 13,  result: "Burnell" },   { min: 14,  max: 14,  result: "Burrow" },
  { min: 15,  max: 15,  result: "Concord" },   { min: 16,  max: 16,  result: "Crux" },
  { min: 17,  max: 17,  result: "Deadrock" },  { min: 18,  max: 18,  result: "Deception" },
  { min: 19,  max: 19,  result: "Elysium" },   { min: 20,  max: 20,  result: "Enigma" },
  { min: 21,  max: 21,  result: "Erebus" },    { min: 22,  max: 22,  result: "Eris" },
  { min: 23,  max: 23,  result: "Evenfall" },  { min: 24,  max: 24,  result: "Eventide" },
  { min: 25,  max: 25,  result: "Farpoint" },  { min: 26,  max: 26,  result: "Felicity" },
  { min: 27,  max: 27,  result: "Florin" },    { min: 28,  max: 28,  result: "Forlorn" },
  { min: 29,  max: 29,  result: "Forsaken" },  { min: 30,  max: 30,  result: "Freya" },
  { min: 31,  max: 31,  result: "Glimmer" },   { min: 32,  max: 32,  result: "Gloam" },
  { min: 33,  max: 33,  result: "Hearth" },    { min: 34,  max: 34,  result: "Helia" },
  { min: 35,  max: 35,  result: "Hypatia" },   { min: 36,  max: 36,  result: "Hyperion" },
  { min: 37,  max: 37,  result: "Janus" },     { min: 38,  max: 38,  result: "Karma" },
  { min: 39,  max: 39,  result: "Kepler" },    { min: 40,  max: 40,  result: "Koshiba" },
  { min: 41,  max: 41,  result: "Lagrange" },  { min: 42,  max: 42,  result: "Larissa" },
  { min: 43,  max: 43,  result: "Lasthope" },  { min: 44,  max: 44,  result: "Lastport" },
  { min: 45,  max: 45,  result: "Legacy" },    { min: 46,  max: 46,  result: "Lodestar" },
  { min: 47,  max: 47,  result: "Luminus" },   { min: 48,  max: 48,  result: "Lyra" },
  { min: 49,  max: 49,  result: "Marrow" },    { min: 50,  max: 50,  result: "Meridian" },
  { min: 51,  max: 51,  result: "Moirai" },    { min: 52,  max: 52,  result: "Mudd" },
  { min: 53,  max: 53,  result: "Neoma" },     { min: 54,  max: 54,  result: "Nerio" },
  { min: 55,  max: 55,  result: "Nova" },      { min: 56,  max: 56,  result: "Nyx" },
  { min: 57,  max: 57,  result: "Osseus" },    { min: 58,  max: 58,  result: "Paradox" },
  { min: 59,  max: 59,  result: "Paragon" },   { min: 60,  max: 60,  result: "Paxton" },
  { min: 61,  max: 61,  result: "Perchance" }, { min: 62,  max: 62,  result: "Pinnacle" },
  { min: 63,  max: 63,  result: "Polaris" },   { min: 64,  max: 64,  result: "Portent" },
  { min: 65,  max: 65,  result: "Prism" },     { min: 66,  max: 66,  result: "Providence" },
  { min: 67,  max: 67,  result: "Purgatory" }, { min: 68,  max: 68,  result: "Rampart" },
  { min: 69,  max: 69,  result: "Ramshackle" },{ min: 70,  max: 70,  result: "Redemption" },
  { min: 71,  max: 71,  result: "Redhaven" },  { min: 72,  max: 72,  result: "Relic" },
  { min: 73,  max: 73,  result: "Reprise" },   { min: 74,  max: 74,  result: "Reverie" },
  { min: 75,  max: 75,  result: "Rhiannon" },  { min: 76,  max: 76,  result: "Rockhome" },
  { min: 77,  max: 77,  result: "Rust" },      { min: 78,  max: 78,  result: "Sagan" },
  { min: 79,  max: 79,  result: "Sanctity" },  { min: 80,  max: 80,  result: "Selena" },
  { min: 81,  max: 81,  result: "Sepulcher" }, { min: 82,  max: 82,  result: "Sigil" },
  { min: 83,  max: 83,  result: "Silvana" },   { min: 84,  max: 84,  result: "Sirius" },
  { min: 85,  max: 85,  result: "Sisyphus" },  { min: 86,  max: 86,  result: "Solitude" },
  { min: 87,  max: 87,  result: "Spire" },     { min: 88,  max: 88,  result: "Starfall" },
  { min: 89,  max: 89,  result: "Summit" },    { min: 90,  max: 90,  result: "Tranquility" },
  { min: 91,  max: 91,  result: "Tyson" },     { min: 92,  max: 92,  result: "Unity" },
  { min: 93,  max: 93,  result: "Utopia" },    { min: 94,  max: 94,  result: "Vega" },
  { min: 95,  max: 95,  result: "Vesper" },    { min: 96,  max: 96,  result: "Wayward" },
  { min: 97,  max: 97,  result: "Welkin" },    { min: 98,  max: 98,  result: "Wellspring" },
  { min: 99,  max: 99,  result: "Weyland" },   { min: 100, max: 100, result: "Wreck" },
];
