/**
 * src/oracles/tables/space.js
 * Space Sighting, Sector Name, Stellar Objects, Spaceborne Peril/Opportunity
 * Source: Starforged Reference Guide pp.32-37
 */

export const SPACE_SIGHTING_TERMINUS = [
  { min: 1,   max: 15,  result: "Stellar Object", ref: "stellar_object" },
  { min: 16,  max: 35,  result: "Planet", ref: "planet_type" },
  { min: 36,  max: 40,  result: "Settlement", ref: "settlement_location" },
  { min: 41,  max: 47,  result: "Starship", ref: "starship_type" },
  { min: 48,  max: 51,  result: "Derelict", ref: "derelict_location" },
  { min: 52,  max: 53,  result: "Precursor Vault", ref: "vault_location" },
  { min: 54,  max: 55,  result: "Creature", ref: "creature_environment" },
  { min: 56,  max: 60,  result: "Descriptor + Focus", ref: "descriptor_focus" },
  { min: 61,  max: 65,  result: "Debris field: Mineral asteroids" },
  { min: 66,  max: 68,  result: "Debris field: Frozen asteroids" },
  { min: 69,  max: 70,  result: "Debris field: Crystalline asteroids" },
  { min: 71,  max: 72,  result: "Debris field: Creature boneyard" },
  { min: 73,  max: 74,  result: "Debris field: Metallic wreckage" },
  { min: 75,  max: 76,  result: "Large rogue asteroid" },
  { min: 77,  max: 78,  result: "Comet with a tail of ionized gas" },
  { min: 79,  max: 81,  result: "Fiery energy storm" },
  { min: 82,  max: 83,  result: "Chaotic meteoroid storm" },
  { min: 84,  max: 85,  result: "Turbulent gravitational wave" },
  { min: 86,  max: 93,  result: "Dense nebula cloud" },
  { min: 94,  max: 98,  result: "Roll twice" },
  { min: 99,  max: 100, result: "Roll three times" },
];

export const SPACE_SIGHTING_OUTLANDS = [
  { min: 1,   max: 15,  result: "Stellar Object", ref: "stellar_object" },
  { min: 16,  max: 35,  result: "Planet", ref: "planet_type" },
  { min: 36,  max: 38,  result: "Settlement", ref: "settlement_location" },
  { min: 39,  max: 43,  result: "Starship", ref: "starship_type" },
  { min: 44,  max: 46,  result: "Derelict", ref: "derelict_location" },
  { min: 47,  max: 49,  result: "Precursor Vault", ref: "vault_location" },
  { min: 50,  max: 52,  result: "Creature", ref: "creature_environment" },
  { min: 53,  max: 58,  result: "Descriptor + Focus", ref: "descriptor_focus" },
  { min: 59,  max: 63,  result: "Debris field: Mineral asteroids" },
  { min: 64,  max: 66,  result: "Debris field: Frozen asteroids" },
  { min: 67,  max: 68,  result: "Debris field: Crystalline asteroids" },
  { min: 69,  max: 70,  result: "Debris field: Creature boneyard" },
  { min: 71,  max: 72,  result: "Debris field: Metallic wreckage" },
  { min: 73,  max: 74,  result: "Large rogue asteroid" },
  { min: 75,  max: 76,  result: "Comet with a tail of ionized gas" },
  { min: 77,  max: 80,  result: "Fiery energy storm" },
  { min: 81,  max: 82,  result: "Chaotic meteoroid storm" },
  { min: 83,  max: 85,  result: "Turbulent gravitational wave" },
  { min: 86,  max: 93,  result: "Dense nebula cloud" },
  { min: 94,  max: 98,  result: "Roll twice" },
  { min: 99,  max: 100, result: "Roll three times" },
];

export const SPACE_SIGHTING_EXPANSE = [
  { min: 1,   max: 15,  result: "Stellar Object", ref: "stellar_object" },
  { min: 16,  max: 35,  result: "Planet", ref: "planet_type" },
  { min: 36,  max: 37,  result: "Settlement", ref: "settlement_location" },
  { min: 38,  max: 39,  result: "Starship", ref: "starship_type" },
  { min: 40,  max: 41,  result: "Derelict", ref: "derelict_location" },
  { min: 42,  max: 45,  result: "Precursor Vault", ref: "vault_location" },
  { min: 46,  max: 49,  result: "Creature", ref: "creature_environment" },
  { min: 50,  max: 56,  result: "Descriptor + Focus", ref: "descriptor_focus" },
  { min: 57,  max: 61,  result: "Debris field: Mineral asteroids" },
  { min: 62,  max: 64,  result: "Debris field: Frozen asteroids" },
  { min: 65,  max: 66,  result: "Debris field: Crystalline asteroids" },
  { min: 67,  max: 68,  result: "Debris field: Creature boneyard" },
  { min: 69,  max: 70,  result: "Debris field: Metallic wreckage" },
  { min: 71,  max: 72,  result: "Large rogue asteroid" },
  { min: 73,  max: 74,  result: "Comet with a tail of ionized gas" },
  { min: 75,  max: 79,  result: "Fiery energy storm" },
  { min: 80,  max: 81,  result: "Chaotic meteoroid storm" },
  { min: 82,  max: 85,  result: "Turbulent gravitational wave" },
  { min: 86,  max: 93,  result: "Dense nebula cloud" },
  { min: 94,  max: 98,  result: "Roll twice" },
  { min: 99,  max: 100, result: "Roll three times" },
];

export const SECTOR_NAME_PREFIX = [
  { min: 1,   max: 2,   result: "Accursed" },  { min: 3,   max: 4,   result: "Ashen" },
  { min: 5,   max: 6,   result: "Asteria" },   { min: 7,   max: 8,   result: "Bitter" },
  { min: 9,   max: 10,  result: "Blighted" },  { min: 11,  max: 12,  result: "Bloodied" },
  { min: 13,  max: 14,  result: "Boundless" }, { min: 15,  max: 16,  result: "Burning" },
  { min: 17,  max: 18,  result: "Cortana" },   { min: 19,  max: 20,  result: "Corvus" },
  { min: 21,  max: 22,  result: "Crimson" },   { min: 23,  max: 24,  result: "Cygnus" },
  { min: 25,  max: 26,  result: "Delphi" },    { min: 27,  max: 28,  result: "Delphian" },
  { min: 29,  max: 30,  result: "Devil's" },   { min: 31,  max: 32,  result: "Ebon" },
  { min: 33,  max: 34,  result: "Essus" },     { min: 35,  max: 36,  result: "Fallen" },
  { min: 37,  max: 38,  result: "Ferrous" },   { min: 39,  max: 40,  result: "Fool's" },
  { min: 41,  max: 42,  result: "Forgotten" }, { min: 43,  max: 44,  result: "Haunted" },
  { min: 45,  max: 46,  result: "Hidden" },    { min: 47,  max: 48,  result: "Hollow" },
  { min: 49,  max: 50,  result: "Igneous" },   { min: 51,  max: 52,  result: "Infernal" },
  { min: 53,  max: 54,  result: "Invidia" },   { min: 55,  max: 56,  result: "Iron" },
  { min: 57,  max: 58,  result: "Kalidas" },   { min: 59,  max: 60,  result: "Kronos" },
  { min: 61,  max: 62,  result: "Lacuna" },    { min: 63,  max: 64,  result: "Lumen" },
  { min: 65,  max: 66,  result: "Mobius" },    { min: 67,  max: 68,  result: "Morien" },
  { min: 69,  max: 70,  result: "Onyx" },      { min: 71,  max: 72,  result: "Outer" },
  { min: 73,  max: 74,  result: "Sanguis" },   { min: 75,  max: 76,  result: "Scarred" },
  { min: 77,  max: 78,  result: "Scorched" },  { min: 79,  max: 80,  result: "Shattered" },
  { min: 81,  max: 82,  result: "Shrouded" },  { min: 83,  max: 84,  result: "Sindri" },
  { min: 85,  max: 86,  result: "Solana" },    { min: 87,  max: 88,  result: "Stygian" },
  { min: 89,  max: 90,  result: "Sulaco" },    { min: 91,  max: 92,  result: "Sundered" },
  { min: 93,  max: 94,  result: "Thunor" },    { min: 95,  max: 96,  result: "Vanguard" },
  { min: 97,  max: 98,  result: "Veiled" },    { min: 99,  max: 100, result: "Wasted" },
];

export const SECTOR_NAME_SUFFIX = [
  { min: 1,   max: 2,   result: "Abyss" },    { min: 3,   max: 4,   result: "Anvil" },
  { min: 5,   max: 6,   result: "Arch" },     { min: 7,   max: 8,   result: "Breach" },
  { min: 9,   max: 10,  result: "Chain" },    { min: 11,  max: 12,  result: "Channel" },
  { min: 13,  max: 14,  result: "Chasm" },    { min: 15,  max: 16,  result: "Circlet" },
  { min: 17,  max: 18,  result: "Cluster" },  { min: 19,  max: 20,  result: "Crown" },
  { min: 21,  max: 22,  result: "Currents" }, { min: 23,  max: 24,  result: "Deep" },
  { min: 25,  max: 26,  result: "Desolation" },{ min: 27, max: 28,  result: "Drift" },
  { min: 29,  max: 30,  result: "Flow" },     { min: 31,  max: 32,  result: "Flux" },
  { min: 33,  max: 34,  result: "Gap" },      { min: 35,  max: 36,  result: "Gate" },
  { min: 37,  max: 38,  result: "Gyre" },     { min: 39,  max: 40,  result: "Heart" },
  { min: 41,  max: 42,  result: "Helix" },    { min: 43,  max: 44,  result: "Juncture" },
  { min: 45,  max: 46,  result: "Lacuna" },   { min: 47,  max: 48,  result: "Limits" },
  { min: 49,  max: 50,  result: "Locus" },    { min: 51,  max: 52,  result: "Maelstrom" },
  { min: 53,  max: 54,  result: "Margin" },   { min: 55,  max: 56,  result: "Maw" },
  { min: 57,  max: 58,  result: "Maze" },     { min: 59,  max: 60,  result: "Nexus" },
  { min: 61,  max: 62,  result: "Oasis" },    { min: 63,  max: 64,  result: "Pass" },
  { min: 65,  max: 66,  result: "Pit" },      { min: 67,  max: 68,  result: "Pyre" },
  { min: 69,  max: 70,  result: "Reach" },    { min: 71,  max: 72,  result: "Rest" },
  { min: 73,  max: 74,  result: "Rift" },     { min: 75,  max: 76,  result: "Sanctum" },
  { min: 77,  max: 78,  result: "Shallows" }, { min: 79,  max: 80,  result: "Shoal" },
  { min: 81,  max: 82,  result: "Spine" },    { min: 83,  max: 84,  result: "Straits" },
  { min: 85,  max: 86,  result: "Threshold" },{ min: 87,  max: 88,  result: "Tide" },
  { min: 89,  max: 90,  result: "Verge" },    { min: 91,  max: 92,  result: "Vertex" },
  { min: 93,  max: 94,  result: "Vigil" },    { min: 95,  max: 96,  result: "Void" },
  { min: 97,  max: 98,  result: "Web" },      { min: 99,  max: 100, result: "Zenith" },
];

export const STELLAR_OBJECT = [
  { min: 1,   max: 15,  result: "Smoldering red star" },
  { min: 16,  max: 30,  result: "Glowing orange star" },
  { min: 31,  max: 45,  result: "Burning yellow star" },
  { min: 46,  max: 50,  result: "Blazing blue star" },
  { min: 51,  max: 60,  result: "Young star incubating in a molecular cloud" },
  { min: 61,  max: 70,  result: "White dwarf shining with spectral light" },
  { min: 71,  max: 75,  result: "Corrupted star radiating with unnatural light" },
  { min: 76,  max: 80,  result: "Neutron star surrounded by intense magnetic fields" },
  { min: 81,  max: 85,  result: "Two stars in close orbit connected by fiery tendrils of energy" },
  { min: 86,  max: 90,  result: "Black hole allows nothing to escape—not even light" },
  { min: 91,  max: 98,  result: "Hypergiant star generating turbulent solar winds" },
  { min: 99,  max: 99,  result: "Artificial star constructed by a long-dead civilization" },
  { min: 100, max: 100, result: "Unstable star showing signs of impending supernova" },
];

export const SPACEBORNE_PERIL = [
  { min: 1,   max: 3,   result: "Artificial gravity generator malfunctions" },
  { min: 4,   max: 6,   result: "Automated defenses or mines protect this area" },
  { min: 7,   max: 9,   result: "Compartment catches fire or is breached" },
  { min: 10,  max: 12,  result: "Contagion or illness threatens to take hold" },
  { min: 13,  max: 15,  result: "Dust clouds imperil navigation or conceal foes" },
  { min: 16,  max: 18,  result: "Energy storm looms" },
  { min: 19,  max: 21,  result: "Familiar foe appears or sends an ominous message" },
  { min: 22,  max: 24,  result: "Gravity well or vortex takes hold" },
  { min: 25,  max: 27,  result: "Imperiled ship calls for help" },
  { min: 28,  max: 30,  result: "Important device fails or malfunctions" },
  { min: 31,  max: 33,  result: "Infestation is revealed" },
  { min: 34,  max: 36,  result: "Intruder or stowaway creates trouble" },
  { min: 37,  max: 39,  result: "Isolation or fear presses in" },
  { min: 40,  max: 42,  result: "Life support system malfunctions" },
  { min: 43,  max: 45,  result: "Meteoroid storm fills the sky" },
  { min: 46,  max: 48,  result: "Mysterious wreckage portends a new threat" },
  { min: 49,  max: 51,  result: "Nearby settlement calls for help" },
  { min: 52,  max: 54,  result: "Old repair or patch fails" },
  { min: 55,  max: 57,  result: "Onboard dispute or inner turmoil causes a disruption" },
  { min: 58,  max: 60,  result: "Others obstruct your path or form a blockade" },
  { min: 61,  max: 63,  result: "Phantom signals suggest a lurking foe" },
  { min: 64,  max: 66,  result: "Pirates hunt for prey" },
  { min: 67,  max: 69,  result: "Power fails" },
  { min: 70,  max: 72,  result: "Primary drive or generator malfunctions" },
  { min: 73,  max: 75,  result: "Sabotage is revealed" },
  { min: 76,  max: 78,  result: "Shockwave or gravity wave approaches" },
  { min: 79,  max: 81,  result: "Someone questions your presence here" },
  { min: 82,  max: 84,  result: "Stellar anomaly emits hazardous energies" },
  { min: 85,  max: 87,  result: "Threatening lifeform draws near" },
  { min: 88,  max: 90,  result: "Troubling visions or apparitions" },
  { min: 91,  max: 93,  result: "True nature of a cargo, occupant, or passenger is revealed" },
  { min: 94,  max: 96,  result: "Unsettling sounds or disturbances" },
  { min: 97,  max: 99,  result: "Action + Theme", ref: "action_theme" },
  { min: 100, max: 100, result: "Roll twice" },
];

export const SPACEBORNE_OPPORTUNITY = [
  { min: 1,   max: 4,   result: "Advance warning of an environmental threat" },
  { min: 5,   max: 8,   result: "Automated signal offers a helpful message or warning" },
  { min: 9,   max: 12,  result: "Cache of cargo or supplies" },
  { min: 13,  max: 16,  result: "Chance for fellowship or a moment of inner peace" },
  { min: 17,  max: 20,  result: "Clear path through otherwise perilous space" },
  { min: 21,  max: 24,  result: "Clue offers insight into a current quest or mystery" },
  { min: 25,  max: 28,  result: "Clue to a lifeform's nature or vulnerabilities" },
  { min: 29,  max: 32,  result: "Derelict ripe for the picking" },
  { min: 33,  max: 36,  result: "Foe inadvertently reveals themselves or tips their hand" },
  { min: 37,  max: 40,  result: "Friendly interaction with a benign lifeform" },
  { min: 41,  max: 44,  result: "Friendly settlement in range" },
  { min: 45,  max: 48,  result: "Friendly spacers at work here" },
  { min: 49,  max: 52,  result: "Friendly starship crosses your path" },
  { min: 53,  max: 56,  result: "Helpful or encouraging message from an acquaintance" },
  { min: 57,  max: 60,  result: "Impressive vista offers comfort or inspiration" },
  { min: 61,  max: 64,  result: "Interesting site offers opportunities for exploration" },
  { min: 65,  max: 68,  result: "Mineral or energy resource detected" },
  { min: 69,  max: 72,  result: "Navigational or environmental hazard is left behind" },
  { min: 73,  max: 76,  result: "Opening to escape or avoid foes" },
  { min: 77,  max: 80,  result: "Plea for help from a potential benefactor" },
  { min: 81,  max: 84,  result: "Probe or beacon with useful data" },
  { min: 85,  max: 88,  result: "Refuge offers a place to hide, plan, or recover" },
  { min: 89,  max: 92,  result: "Sensors pinpoint a lurking foe" },
  { min: 93,  max: 96,  result: "Sensors reveal helpful or interesting environmental data" },
  { min: 97,  max: 100, result: "Vehicle or equipment performs beyond expectations" },
];
