/**
 * src/oracles/tables/starships.js
 * Source: Starforged Reference Guide pp.58-61
 */

export const TYPE = [
  { min: 1,   max: 2,   result: "Carrier — Launches fighters" },
  { min: 3,   max: 6,   result: "Corvette — Light attack ship" },
  { min: 7,   max: 11,  result: "Courier — Fast transport" },
  { min: 12,  max: 14,  result: "Cruiser — Medium attack ship" },
  { min: 15,  max: 16,  result: "Dreadnought — Heavy attack ship" },
  { min: 17,  max: 19,  result: "Escape pod — Survival craft" },
  { min: 20,  max: 22,  result: "Foundry — Mobile construction platform" },
  { min: 23,  max: 27,  result: "Harvester — Fuel or energy excavator" },
  { min: 28,  max: 33,  result: "Hauler — Heavy transport" },
  { min: 34,  max: 36,  result: "Hunter — Stealthy attack ship" },
  { min: 37,  max: 38,  result: "Ironhome — Habitat" },
  { min: 39,  max: 42,  result: "Mender — Utility or repair" },
  { min: 43,  max: 47,  result: "Outbounder — Remote survey or research" },
  { min: 48,  max: 50,  result: "Pennant — Command ship" },
  { min: 51,  max: 56,  result: "Prospector — Mineral excavator" },
  { min: 57,  max: 61,  result: "Reclaimer — Salvage or rescue" },
  { min: 62,  max: 64,  result: "Shuttle — Short-range transport" },
  { min: 65,  max: 67,  result: "Snub fighter — Small attack craft" },
  { min: 68,  max: 82,  result: "Multipurpose", ref: "starship_mission_terminus" },
  { min: 83,  max: 84,  result: "Unusual or unknown" },
  { min: 85,  max: 94,  result: "Fleet", ref: "fleet" },
  { min: 95,  max: 100, result: "Ships in conflict (roll twice)" },
];

export const FIRST_LOOK = [
  { min: 1,   max: 4,   result: "Abnormal sensor readings" },
  { min: 5,   max: 8,   result: "Brightly painted" },
  { min: 9,   max: 13,  result: "Bristling with weapons" },
  { min: 14,  max: 18,  result: "Dark or stealthy" },
  { min: 19,  max: 23,  result: "Heavy armor" },
  { min: 24,  max: 28,  result: "Immobile" },
  { min: 29,  max: 33,  result: "Intimidating profile" },
  { min: 34,  max: 37,  result: "Large sensor arrays" },
  { min: 38,  max: 41,  result: "Leaking radiation" },
  { min: 42,  max: 45,  result: "Low-profile or disguised" },
  { min: 46,  max: 49,  result: "Modern or advanced design" },
  { min: 50,  max: 54,  result: "Obsolete design" },
  { min: 55,  max: 59,  result: "Obvious damage" },
  { min: 60,  max: 63,  result: "Biological components" },
  { min: 64,  max: 67,  result: "Ornate markings" },
  { min: 68,  max: 71,  result: "Oversized engines" },
  { min: 72,  max: 75,  result: "Prominent guild emblem" },
  { min: 76,  max: 80,  result: "Refitted or repurposed hull" },
  { min: 81,  max: 85,  result: "Scarred hull" },
  { min: 86,  max: 90,  result: "Built from scrap" },
  { min: 91,  max: 94,  result: "Towing or linked" },
  { min: 95,  max: 100, result: "Descriptor + Focus", ref: "descriptor_focus" },
];

export const INITIAL_CONTACT = [
  { min: 1,   max: 3,   result: "Familiar" },
  { min: 4,   max: 15,  result: "Friendly" },
  { min: 16,  max: 25,  result: "Neutral / automated" },
  { min: 26,  max: 35,  result: "Wary" },
  { min: 36,  max: 40,  result: "Dismissive" },
  { min: 41,  max: 50,  result: "Uncooperative" },
  { min: 51,  max: 65,  result: "Hostile" },
  { min: 66,  max: 80,  result: "Asking for help" },
  { min: 81,  max: 85,  result: "In battle" },
  { min: 86,  max: 90,  result: "Unresponsive" },
  { min: 91,  max: 95,  result: "Destroyed" },
  { min: 96,  max: 100, result: "Derelict", ref: "derelict_location" },
];

export const FLEET = [
  { min: 1,  max: 10,  result: "Battle fleet" },
  { min: 11, max: 25,  result: "Pirate wing" },
  { min: 26, max: 35,  result: "Raider horde" },
  { min: 36, max: 50,  result: "Salvager hive" },
  { min: 51, max: 60,  result: "Settler caravan" },
  { min: 61, max: 70,  result: "Trade caravan" },
  { min: 71, max: 90,  result: "Transport and escorts" },
  { min: 91, max: 100, result: "Starship Mission", ref: "starship_mission_terminus" },
];

export const MISSION_TERMINUS = [
  { min: 1,  max: 3,   result: "Blockade a location" },
  { min: 4,  max: 6,   result: "Break a blockade" },
  { min: 7,  max: 9,   result: "Collect a resource" },
  { min: 10, max: 11,  result: "Command others" },
  { min: 12, max: 14,  result: "Conduct diplomacy" },
  { min: 15, max: 17,  result: "Conduct espionage" },
  { min: 18, max: 20,  result: "Conduct piracy" },
  { min: 21, max: 23,  result: "Conduct research" },
  { min: 24, max: 26,  result: "Defend against an attack" },
  { min: 27, max: 29,  result: "Deliver messages or data" },
  { min: 30, max: 32,  result: "Establish a settlement" },
  { min: 33, max: 35,  result: "Evacuate a location" },
  { min: 36, max: 37,  result: "Explore a region" },
  { min: 38, max: 39,  result: "Hold prisoners" },
  { min: 40, max: 42,  result: "Hunt down another ship" },
  { min: 43, max: 45,  result: "Launch an attack" },
  { min: 46, max: 48,  result: "Patrol an area" },
  { min: 49, max: 51,  result: "Provide medical aid" },
  { min: 52, max: 54,  result: "Provide repairs" },
  { min: 55, max: 57,  result: "Provide shelter" },
  { min: 58, max: 59,  result: "Quarantine a danger" },
  { min: 60, max: 62,  result: "Raid a settlement" },
  { min: 63, max: 65,  result: "Resupply a settlement" },
  { min: 66, max: 68,  result: "Retrieve salvage" },
  { min: 69, max: 71,  result: "Search and rescue" },
  { min: 72, max: 74,  result: "Smuggle cargo" },
  { min: 75, max: 77,  result: "Survey a site" },
  { min: 78, max: 79,  result: "Test a technology" },
  { min: 80, max: 82,  result: "Transport cargo" },
  { min: 83, max: 85,  result: "Transport passengers" },
  { min: 86, max: 90,  result: "Action + Theme", ref: "action_theme" },
  { min: 91, max: 100, result: "Roll twice" },
];

// Outlands and Expanse have slightly different distributions; using Terminus as default
export const MISSION_OUTLANDS = MISSION_TERMINUS;
export const MISSION_EXPANSE  = MISSION_TERMINUS;

export const NAMES = [
  { min: 1,   max: 1,   result: "Arclight" },         { min: 2,   max: 2,   result: "Argent Arrow" },
  { min: 3,   max: 3,   result: "Artemis" },           { min: 4,   max: 4,   result: "Astral Explorer" },
  { min: 5,   max: 5,   result: "Atlas" },             { min: 6,   max: 6,   result: "Aurora" },
  { min: 7,   max: 7,   result: "Avari's Wake" },      { min: 8,   max: 8,   result: "Banshee's Cry" },
  { min: 9,   max: 9,   result: "Beowulf" },           { min: 10,  max: 10,  result: "Bloody Jaw" },
  { min: 11,  max: 11,  result: "Broken Sword" },      { min: 12,  max: 12,  result: "Buccaneer" },
  { min: 13,  max: 13,  result: "Cerelis Nine" },      { min: 14,  max: 14,  result: "Clarion Call" },
  { min: 15,  max: 15,  result: "Dawn's Herald" },     { min: 16,  max: 16,  result: "Dead Reckoning" },
  { min: 17,  max: 17,  result: "Drift Runner" },      { min: 18,  max: 18,  result: "Eclipse" },
  { min: 19,  max: 19,  result: "Elara Five" },        { min: 20,  max: 20,  result: "Enchantress" },
  { min: 21,  max: 21,  result: "Endurance" },         { min: 22,  max: 22,  result: "Excalibur" },
  { min: 23,  max: 23,  result: "Eye of the Void" },   { min: 24,  max: 24,  result: "Fall of Icarus" },
  { min: 25,  max: 25,  result: "Fallen Light" },      { min: 26,  max: 26,  result: "False Hope" },
  { min: 27,  max: 27,  result: "Firebreak" },         { min: 28,  max: 28,  result: "First Light" },
  { min: 29,  max: 29,  result: "Forge Flier" },       { min: 30,  max: 30,  result: "Fortune's Favor" },
  { min: 31,  max: 31,  result: "Freya's Wrath" },     { min: 32,  max: 32,  result: "Ghost" },
  { min: 33,  max: 33,  result: "Guiding Star" },      { min: 34,  max: 34,  result: "Hand of Fate" },
  { min: 35,  max: 35,  result: "Herald of Doom" },    { min: 36,  max: 36,  result: "Implacable" },
  { min: 37,  max: 37,  result: "Implicit" },          { min: 38,  max: 38,  result: "Inferno" },
  { min: 39,  max: 39,  result: "Invictus" },          { min: 40,  max: 40,  result: "Iron Cairn" },
  { min: 41,  max: 41,  result: "Karena's Reverie" },  { min: 42,  max: 42,  result: "Kraken" },
  { min: 43,  max: 43,  result: "Kuno's Hammer" },     { min: 44,  max: 44,  result: "Lightline" },
  { min: 45,  max: 45,  result: "Lodestar" },          { min: 46,  max: 46,  result: "Long Haul" },
  { min: 47,  max: 47,  result: "Lost Fortune" },      { min: 48,  max: 48,  result: "Luminous Sorrow" },
  { min: 49,  max: 49,  result: "Manta" },             { min: 50,  max: 50,  result: "Mercy" },
  { min: 51,  max: 51,  result: "Mutara" },            { min: 52,  max: 52,  result: "Nebula Prowler" },
  { min: 53,  max: 53,  result: "Newton's Folly" },    { min: 54,  max: 54,  result: "Nightfall" },
  { min: 55,  max: 55,  result: "Nomad" },             { min: 56,  max: 56,  result: "Obsidian Trident" },
  { min: 57,  max: 57,  result: "Onslaught" },         { min: 58,  max: 58,  result: "Orca" },
  { min: 59,  max: 59,  result: "Outward Bound" },     { min: 60,  max: 60,  result: "Phantom" },
  { min: 61,  max: 61,  result: "Photon" },            { min: 62,  max: 62,  result: "Poltergeist" },
  { min: 63,  max: 63,  result: "Profit Margin" },     { min: 64,  max: 64,  result: "Raven's Call" },
  { min: 65,  max: 65,  result: "Raya's Promise" },    { min: 66,  max: 66,  result: "Reaper" },
  { min: 67,  max: 67,  result: "Reforged Hope" },     { min: 68,  max: 68,  result: "Relentless" },
  { min: 69,  max: 69,  result: "Royal Signet" },      { min: 70,  max: 70,  result: "Rubicon" },
  { min: 71,  max: 71,  result: "Sareea's Tribute" },  { min: 72,  max: 72,  result: "Second Chance" },
  { min: 73,  max: 73,  result: "Shard of the Sun" },  { min: 74,  max: 74,  result: "Shattered Siege" },
  { min: 75,  max: 75,  result: "Shattered Star" },    { min: 76,  max: 76,  result: "Silver Talon" },
  { min: 77,  max: 77,  result: "Smoldering Flame" },  { min: 78,  max: 78,  result: "Sovereign Skies" },
  { min: 79,  max: 79,  result: "Sparrowhawk" },       { min: 80,  max: 80,  result: "Stardust" },
  { min: 81,  max: 81,  result: "Starfall" },          { min: 82,  max: 82,  result: "Stellar Hawk" },
  { min: 83,  max: 83,  result: "Stormswept" },        { min: 84,  max: 84,  result: "Sundered Aegis" },
  { min: 85,  max: 85,  result: "Sundown" },           { min: 86,  max: 86,  result: "Sureshot" },
  { min: 87,  max: 87,  result: "Terminus Clipper" },  { min: 88,  max: 88,  result: "Terrapin" },
  { min: 89,  max: 89,  result: "Timber Wolf" },       { min: 90,  max: 90,  result: "Tip of the Spear" },
  { min: 91,  max: 91,  result: "Titan" },             { min: 92,  max: 92,  result: "Tormentor" },
  { min: 93,  max: 93,  result: "Trithia Six" },       { min: 94,  max: 94,  result: "Ultraviolet" },
  { min: 95,  max: 95,  result: "Valora's Comet" },    { min: 96,  max: 96,  result: "Vengeance" },
  { min: 97,  max: 97,  result: "Venture" },           { min: 98,  max: 98,  result: "Vigilant" },
  { min: 99,  max: 99,  result: "Voidtreader" },       { min: 100, max: 100, result: "Vulture" },
];
