/**
 * src/oracles/tables/vaults.js
 * Precursor Vaults (aka Precursor Vault oracles)
 * Source: Starforged Reference Guide pp.92-99
 */

export const LOCATION = [
  { min: 1,  max: 50,  result: "Planetside" },
  { min: 51, max: 75,  result: "Orbital" },
  { min: 76, max: 100, result: "Deep Space" },
];

export const SCALE = [
  { min: 1,  max: 30,  result: "Minor, confined site" },
  { min: 31, max: 65,  result: "Typical site of limited scope" },
  { min: 66, max: 90,  result: "Large, elaborate site" },
  { min: 91, max: 99,  result: "Vast site of unfathomable complexity" },
  { min: 100,max: 100, result: "World-spanning site or megastructure" },
];

export const FORM = [
  { min: 1,  max: 35,  result: "Structure" },
  { min: 36, max: 60,  result: "Vessel" },
  { min: 61, max: 80,  result: "Monument" },
  { min: 81, max: 95,  result: "Machine" },
  { min: 96, max: 100, result: "Incomprehensible" },
];

export const SHAPE = [
  { min: 1,  max: 15,  result: "Practical or functional" },
  { min: 16, max: 20,  result: "Geometric (complex shape)" },
  { min: 21, max: 25,  result: "Geometric (cube)" },
  { min: 26, max: 30,  result: "Geometric (obelisk)" },
  { min: 31, max: 35,  result: "Geometric (pyramid)" },
  { min: 36, max: 40,  result: "Geometric (ring or torus)" },
  { min: 41, max: 45,  result: "Geometric (sphere)" },
  { min: 46, max: 55,  result: "Organic or curved" },
  { min: 56, max: 60,  result: "Platform or disc" },
  { min: 61, max: 65,  result: "Spires or towers" },
  { min: 66, max: 68,  result: "Domed" },
  { min: 69, max: 73,  result: "Spiky" },
  { min: 74, max: 76,  result: "Sculptural or effigy" },
  { min: 77, max: 79,  result: "Amorphous" },
  { min: 80, max: 85,  result: "Transforming" },
  { min: 86, max: 100, result: "Roll twice" },
];

export const MATERIAL = [
  { min: 1,  max: 30,  result: "Metallic (industrial)" },
  { min: 31, max: 60,  result: "Metallic (smooth)" },
  { min: 61, max: 70,  result: "Rocky or stone-like" },
  { min: 71, max: 74,  result: "Crystalline or glass-like" },
  { min: 75, max: 78,  result: "Bone-like" },
  { min: 79, max: 82,  result: "Flesh-like" },
  { min: 83, max: 86,  result: "Plant-like" },
  { min: 87, max: 88,  result: "Energy" },
  { min: 89, max: 90,  result: "Liquid" },
  { min: 91, max: 100, result: "Roll twice" },
];

export const OUTER_FIRST_LOOK = [
  { min: 1,  max: 3,   result: "Corrupting its environment" },
  { min: 4,  max: 7,   result: "Automated defenses" },
  { min: 8,  max: 10,  result: "Breached exterior" },
  { min: 11, max: 14,  result: "Broken or fragmented" },
  { min: 15, max: 17,  result: "Camouflaged or hidden" },
  { min: 18, max: 20,  result: "Cavernous opening" },
  { min: 21, max: 23,  result: "Dispersed structures" },
  { min: 24, max: 26,  result: "Dreadful premonitions" },
  { min: 27, max: 30,  result: "Electromagnetic field" },
  { min: 31, max: 33,  result: "Embedded within terrain" },
  { min: 34, max: 36,  result: "Encased in an energy field" },
  { min: 37, max: 40,  result: "Energy core or conduit" },
  { min: 41, max: 43,  result: "Fractal patterns" },
  { min: 44, max: 47,  result: "Glyphs or symbols" },
  { min: 48, max: 51,  result: "Hazardous readings" },
  { min: 52, max: 54,  result: "Levitating or in motion" },
  { min: 55, max: 58,  result: "Lighted or illuminated" },
  { min: 59, max: 61,  result: "No obvious point of entry" },
  { min: 62, max: 64,  result: "Overgrown or entangled" },
  { min: 65, max: 67,  result: "Perfectly preserved" },
  { min: 68, max: 70,  result: "Phasing in and out of reality" },
  { min: 71, max: 73,  result: "Physical barrier" },
  { min: 74, max: 76,  result: "Pitted or scarred" },
  { min: 77, max: 79,  result: "Scaled for outsized beings" },
  { min: 80, max: 82,  result: "Shrouded in mist or haze" },
  { min: 83, max: 85,  result: "Signs of invaders" },
  { min: 86, max: 89,  result: "Sound or signal" },
  { min: 90, max: 92,  result: "Strong gravity well" },
  { min: 93, max: 95,  result: "Surrounded by destruction" },
  { min: 96, max: 100, result: "Descriptor + Focus", ref: "descriptor_focus" },
];

export const INNER_FIRST_LOOK = [
  { min: 1,  max: 3,   result: "Abnormal gravity" },
  { min: 4,  max: 6,   result: "Automated defenses" },
  { min: 7,  max: 9,   result: "Biological infestation" },
  { min: 10, max: 12,  result: "Carried tech is disrupted" },
  { min: 13, max: 15,  result: "Complex textures or patterns" },
  { min: 16, max: 18,  result: "Corpses of intruders" },
  { min: 19, max: 21,  result: "Damage and debris" },
  { min: 22, max: 24,  result: "Deteriorating spaces" },
  { min: 25, max: 27,  result: "Dissonant tones or music" },
  { min: 28, max: 30,  result: "Energy surges" },
  { min: 31, max: 33,  result: "Environment reacts to your presence" },
  { min: 34, max: 36,  result: "Evidence of looting or scavenging" },
  { min: 37, max: 39,  result: "Excessive cold" },
  { min: 40, max: 42,  result: "Excessive heat" },
  { min: 43, max: 45,  result: "Faint ambient lighting" },
  { min: 46, max: 48,  result: "Impenetrable darkness" },
  { min: 49, max: 51,  result: "Intense smell" },
  { min: 52, max: 54,  result: "Magnetic surfaces" },
  { min: 55, max: 57,  result: "Material does not match exterior" },
  { min: 58, max: 60,  result: "Ornate markings or symbols" },
  { min: 61, max: 63,  result: "Reactive lighting responds to your presence" },
  { min: 64, max: 66,  result: "Scale does not match exterior" },
  { min: 67, max: 69,  result: "Signs of invasive lifeforms" },
  { min: 70, max: 72,  result: "Surfaces respond to touch" },
  { min: 73, max: 75,  result: "Thick haze or smoke" },
  { min: 76, max: 78,  result: "Thick or fluid atmosphere" },
  { min: 79, max: 81,  result: "Thrumming or droning sound" },
  { min: 82, max: 84,  result: "Toxic atmosphere" },
  { min: 85, max: 87,  result: "Toxic residue" },
  { min: 88, max: 90,  result: "Well-preserved" },
  { min: 91, max: 93,  result: "Wet or humid" },
  { min: 94, max: 100, result: "Descriptor + Focus", ref: "descriptor_focus" },
];

export const PURPOSE = [
  { min: 1,  max: 3,   result: "Capture or control of other beings" },
  { min: 4,  max: 6,   result: "Command or communication relay" },
  { min: 7,  max: 9,   result: "Commemoration of an event" },
  { min: 10, max: 12,  result: "Conduit to mystical powers" },
  { min: 13, max: 16,  result: "Conservation of living specimens" },
  { min: 17, max: 20,  result: "Containment of a powerful being" },
  { min: 21, max: 24,  result: "Containment of dangerous creatures" },
  { min: 25, max: 27,  result: "Containment of weapons" },
  { min: 28, max: 31,  result: "Control of a destructive weapon" },
  { min: 32, max: 34,  result: "Generation of defenses or barriers" },
  { min: 35, max: 38,  result: "Generation or transformation of energy" },
  { min: 39, max: 41,  result: "Harvesting of resources" },
  { min: 42, max: 44,  result: "Interment of the dead" },
  { min: 45, max: 47,  result: "Manipulation of spacetime" },
  { min: 48, max: 50,  result: "Manufacturing of lifeforms" },
  { min: 51, max: 53,  result: "Manufacturing of machines or devices" },
  { min: 54, max: 56,  result: "Passage to another location" },
  { min: 57, max: 59,  result: "Preservation of an ancient intelligence" },
  { min: 60, max: 62,  result: "Preservation of maps or navigational data" },
  { min: 63, max: 66,  result: "Protection of a sacred artifact" },
  { min: 67, max: 69,  result: "Researching science or technology" },
  { min: 70, max: 73,  result: "Safekeeping of cultural records or memories" },
  { min: 74, max: 77,  result: "Shelter for inhabitants" },
  { min: 78, max: 80,  result: "Stockpiling of resources" },
  { min: 81, max: 83,  result: "Surveying or monitoring of a location" },
  { min: 84, max: 87,  result: "Transformation of terrain or environments" },
  { min: 88, max: 90,  result: "Worship of a god or being" },
  { min: 91, max: 95,  result: "Action + Theme", ref: "action_theme" },
  { min: 96, max: 100, result: "Roll twice" },
];

export const INTERIOR_FEATURE = [
  { min: 1,  max: 3,   result: "Ascending or descending path" },
  { min: 4,  max: 6,   result: "Biological growths" },
  { min: 7,  max: 8,   result: "Blood trail" },
  { min: 9,  max: 10,  result: "Breached or ruptured area" },
  { min: 11, max: 13,  result: "Broken or inactive machinery" },
  { min: 14, max: 15,  result: "Clinging mist" },
  { min: 16, max: 18,  result: "Damage or debris" },
  { min: 19, max: 20,  result: "Echoing noises" },
  { min: 21, max: 22,  result: "Elevated path over chasm or shaft" },
  { min: 23, max: 25,  result: "Energy discharges" },
  { min: 26, max: 28,  result: "Enigmatic controls or terminal" },
  { min: 29, max: 30,  result: "Garden or invasive plant life" },
  { min: 31, max: 32,  result: "Inscrutable object lies dark and silent" },
  { min: 33, max: 35,  result: "Intersection or hub" },
  { min: 36, max: 38,  result: "Intricate symbols or pictographs" },
  { min: 39, max: 41,  result: "Looted or dismantled technology" },
  { min: 42, max: 44,  result: "Looted or empty containers" },
  { min: 45, max: 47,  result: "Mazelike passages" },
  { min: 48, max: 49,  result: "Moving platform or lift" },
  { min: 50, max: 52,  result: "Mummified or decayed corpses" },
  { min: 53, max: 55,  result: "Narrowing or widening path" },
  { min: 56, max: 58,  result: "Pooled liquid" },
  { min: 59, max: 61,  result: "Remains of intruders" },
  { min: 62, max: 63,  result: "Scattered bones" },
  { min: 64, max: 66,  result: "Scrawled markings" },
  { min: 67, max: 68,  result: "Signs of an attack or battle" },
  { min: 69, max: 71,  result: "Signs of invasive creatures" },
  { min: 72, max: 73,  result: "Surfaces honeycombed with openings" },
  { min: 74, max: 76,  result: "Unintelligible recorded message" },
  { min: 77, max: 79,  result: "Unintelligible whispers" },
  { min: 80, max: 82,  result: "Vaulted chamber" },
  { min: 83, max: 85,  result: "Vertical shaft" },
  { min: 86, max: 90,  result: "Transition into the Sanctum" },
  { min: 91, max: 95,  result: "Descriptor + Focus", ref: "descriptor_focus" },
  { min: 96, max: 100, result: "Roll twice" },
];

export const INTERIOR_PERIL = [
  { min: 1,  max: 5,   result: "Broken path" },
  { min: 6,  max: 10,  result: "Change in atmosphere or environment" },
  { min: 11, max: 15,  result: "Corrosive environment" },
  { min: 16, max: 20,  result: "Dire warning left by other explorers" },
  { min: 21, max: 25,  result: "Foes close in" },
  { min: 26, max: 30,  result: "Fragile structural integrity" },
  { min: 31, max: 35,  result: "Hazardous path designed for traversal by other beings" },
  { min: 36, max: 40,  result: "Important gear malfunctions" },
  { min: 41, max: 45,  result: "Isolation or fear presses in" },
  { min: 46, max: 50,  result: "Mechanical trap" },
  { min: 51, max: 55,  result: "Mist or darkness conceals dangers" },
  { min: 56, max: 60,  result: "Puzzling mystery blocks the way" },
  { min: 61, max: 65,  result: "Radioactive hot spot" },
  { min: 66, max: 70,  result: "Rivals seek what lay within" },
  { min: 71, max: 75,  result: "Signs of a contagion" },
  { min: 76, max: 80,  result: "Signs of a lurking foe" },
  { min: 81, max: 85,  result: "Tempting location or object holds hidden dangers" },
  { min: 86, max: 90,  result: "Toxic atmosphere" },
  { min: 91, max: 95,  result: "Unnerving sound or sensation" },
  { min: 96, max: 99,  result: "Action + Theme", ref: "action_theme" },
  { min: 100,max: 100, result: "Roll twice" },
];

export const INTERIOR_OPPORTUNITY = [
  { min: 1,  max: 10,  result: "Clue points the way to your destination or target" },
  { min: 11, max: 20,  result: "Clue to a lifeform's nature or vulnerabilities" },
  { min: 21, max: 30,  result: "Helpful gear left by another explorer" },
  { min: 31, max: 40,  result: "Insight into the nature or history of this site" },
  { min: 41, max: 50,  result: "Intriguing device or artifact" },
  { min: 51, max: 60,  result: "Opening to get the drop on a foe" },
  { min: 61, max: 70,  result: "Opening to outmaneuver or escape a threat or foe" },
  { min: 71, max: 80,  result: "Salvageable resource" },
  { min: 81, max: 90,  result: "Secure area offers a moment of peace" },
  { min: 91, max: 100, result: "Shortcut or less perilous path speeds your way" },
];
