/**
 * STARFORGED COMPANION
 * src/sectors/siteDiscovery.js — Reveal a precursor vault / derelict site.
 *
 * Sites generated by the sector creator start "unexplored": a dim pin behind an
 * undiscovered passage (see precursorSites.js / sceneBuilder.js). Discovery is
 * the payoff for reaching one — finishing an expedition toward it, or a manual
 * GM reveal (`!reveal-site`). Revealing flips the discovery record, marks the
 * location Actor visited, and re-styles the scene pin + passage to their charted
 * appearance.
 *
 * GM-gated by the caller (world-setting writes need GM). Dependency-injected so
 * the orchestration unit-tests without a live game.
 */

import { selectSiteForReveal } from "./precursorSites.js";
import { restyleSiteOnScene }  from "./sceneBuilder.js";
import { updateLocation, getLocation } from "../entities/location.js";

const MODULE_ID = "starforged-companion";

/**
 * Reveal the first undiscovered site (across all stored sectors) matching a
 * destination label. Returns the revealed { sector, site } or null when nothing
 * matched. Persists campaign state only when a site is revealed.
 *
 * @param {string|null} label — expedition destination / command target
 * @param {Object} [opts]
 * @param {string}   [opts.source]    — telemetry tag ("expedition" | "manual")
 * @param {string}   [opts.siteId]    — a stored expedition→site link: reveal
 *   exactly this discovery when it exists, bypassing the name-fuzzy ladder
 *   (2026-07 soft-spot fix — with several undiscovered sites the ladder could
 *   reveal the "wrong" one).
 * @param {Function} [opts.getState]  — () => campaignState
 * @param {Function} [opts.setState]  — (state) => Promise
 * @param {Function} [opts.getScene]  — (sceneId) => Scene|null
 * @param {Function} [opts.updateLoc] — (actorId, updates) => Promise
 * @param {Function} [opts.restyle]   — (scene, site) => Promise
 * @returns {Promise<{sector:Object, site:Object}|null>}
 */
export async function revealSectorSite(label, opts = {}) {
  const getState  = opts.getState  ?? (() => game.settings.get(MODULE_ID, "campaignState"));
  const setState  = opts.setState  ?? (s => game.settings.set(MODULE_ID, "campaignState", s));
  const getScene  = opts.getScene  ?? (id => game.scenes?.get?.(id) ?? null);
  const updateLoc = opts.updateLoc ?? updateLocation;
  const restyle   = opts.restyle   ?? restyleSiteOnScene;

  const state = getState();
  for (const sector of state?.sectors ?? []) {
    const discoveries = sector.mapData?.discoveries ?? [];
    const match = (opts.siteId
        ? discoveries.find(d => d && d.id === opts.siteId && !d.discovered)
        : null)
      ?? selectSiteForReveal(discoveries, label);
    if (!match) continue;

    match.discovered = true;

    if (match.actorId) {
      try { await updateLoc(match.actorId, { status: "visited" }); }
      catch (err) { console.warn(`${MODULE_ID} | revealSectorSite: location status update failed:`, err?.message ?? err); }
    }

    if (sector.sceneId) {
      const scene = getScene(sector.sceneId);
      if (scene) {
        try { await restyle(scene, match); }
        catch (err) { console.warn(`${MODULE_ID} | revealSectorSite: scene restyle failed:`, err?.message ?? err); }
      }
    }

    await setState(state);
    return { sector, site: match };
  }
  return null;
}

/**
 * Post a GM/table-visible card announcing a newly discovered site.
 *
 * @param {{sector:Object, site:Object}} result — revealSectorSite() return
 * @returns {Promise<void>}
 */
export async function postSiteDiscoveryCard(result) {
  const site = result?.site;
  if (!site) return;
  const kind = site.type === "vault" ? "precursor vault" : "derelict";

  // Surface the rolled exterior at the payoff moment (SITE-DISCOVERY-CARD-
  // GENERIC fix, 2026-07): the map discovery record is deliberately light,
  // so read the location Actor's record for the first look. Fail-open — a
  // missing record just renders the original generic line.
  let firstLookLine = "";
  try {
    const record = site.actorId ? getLocation(site.actorId) : null;
    if (record?.firstLook) {
      firstLookLine = `<p><em>${escapeSiteHtml(record.firstLook)}</em></p>`;
    }
  } catch (err) {
    console.debug?.(`${MODULE_ID} | postSiteDiscoveryCard: record read failed:`, err?.message ?? err);
  }

  const content =
    `<div class="starforged-companion-card">` +
    `<h3>◈ Site Discovered — ${site.name}</h3>` +
    `<p>A passage opens through to a ${kind} in the sector's outer reaches. ` +
    `It is now charted on the sector map — undertake an expedition there, or ` +
    `Explore a Waypoint to move through its zones.</p>` +
    firstLookLine +
    `</div>`;
  try {
    await ChatMessage.create({
      content,
      flags: { [MODULE_ID]: { siteDiscovered: true, siteId: site.id, siteType: site.type } },
    });
  } catch (err) {
    console.warn(`${MODULE_ID} | postSiteDiscoveryCard failed:`, err?.message ?? err);
  }
}

/**
 * Mark a DISCOVERED site fully explored (SITE-NO-COMPLETION fix, 2026-07):
 * sets the location Actor's status to "cleared" and stamps the discovery
 * record, closing the unexplored → visited → cleared lifecycle the schema
 * always documented. Same matching ladder as revealSectorSite, over
 * discovered sites that aren't already cleared. GM-gated by the caller.
 *
 * @param {string|null} label
 * @param {Object} [opts] — same injection seams as revealSectorSite
 * @returns {Promise<{sector:Object, site:Object}|null>}
 */
export async function clearSectorSite(label, opts = {}) {
  const getState  = opts.getState  ?? (() => game.settings.get(MODULE_ID, "campaignState"));
  const setState  = opts.setState  ?? (s => game.settings.set(MODULE_ID, "campaignState", s));
  const updateLoc = opts.updateLoc ?? updateLocation;

  const state = getState();
  for (const sector of state?.sectors ?? []) {
    const discoveries = sector.mapData?.discoveries ?? [];
    const eligible = discoveries.filter(d => d && d.discovered && !d.cleared);
    // Reuse the reveal ladder by presenting eligible sites as "undiscovered"
    // candidates (the ladder filters on !discovered).
    const match = selectSiteForReveal(
      eligible.map(d => ({ ...d, discovered: false })),
      label,
    );
    if (!match) continue;
    const record = discoveries.find(d => d && d.id === match.id);
    if (!record) continue;

    record.cleared = true;
    if (record.actorId) {
      try { await updateLoc(record.actorId, { status: "cleared" }); }
      catch (err) { console.warn(`${MODULE_ID} | clearSectorSite: location status update failed:`, err?.message ?? err); }
    }
    await setState(state);
    return { sector, site: record };
  }
  return null;
}

function escapeSiteHtml(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
